import type { FactoryHeroineOption } from '../aiFactoryTypes'

export const DEFAULT_HEROINE_OPTIONS: FactoryHeroineOption[] = [
] = [
  { key: "endure-then-counterattack", label: "Nhẫn nhịn rồi phản công" },
  { key: "cold-revenge", label: "Lạnh lùng trả thù" },
  { key: "soft-outside-hard-inside", label: "Ngoài mềm trong cứng" },
  { key: "legal-rational", label: "Lý trí, giỏi pháp lý" },
  { key: "business-queen", label: "Nữ cường thương chiến" },
  { key: "reborn-one-step-ahead", label: "Tái sinh, đi trước một bước" },
  { key: "protective-mother", label: "Người mẹ bảo vệ con" },
  { key: "wealthy-daughter", label: "Thiên kim hào môn bị xem thường" },
  { key: "silent-evidence", label: "Im lặng gom bằng chứng" },
  { key: "public-face-slap", label: "Vả mặt công khai cực gắt" },
  { key: "pain-to-control", label: "Từ đau khổ thành kiểm soát thế cục" },
  { key: "calm-strategist", label: "Bình tĩnh thao túng thế cục" },
  { key: "single-mother-warrior", label: "Mẹ đơn thân kiên cường" },
  { key: "hidden-rich-heiress", label: "Giàu ngầm nhưng giả yếu thế" },
  { key: "public-relations-master", label: "Giỏi truyền thông đảo chiều dư luận" },
  { key: "evidence-collector", label: "Thu thập chứng cứ từng bước" },
  { key: "quiet-lawful-revenge", label: "Trả thù hợp pháp, không ồn ào" },
  { key: "career-first", label: "Sự nghiệp trên hết, tình yêu đứng sau" },
  { key: "wounded-but-sharp", label: "Tổn thương nhưng sắc bén" },
  { key: "gentle-deadly", label: "Dịu dàng nhưng ra tay rất đau" },
  { key: "luat-su-ly-hon-lanh-dau", label: "Luật sư ly hôn lạnh đầu" },
  { key: "bac-si-gioi-bi-vu-oan", label: "Bác sĩ giỏi bị vu oan" },
  { key: "nu-chu-tich-an-danh", label: "Nữ chủ tịch ẩn danh" },
  { key: "thu-ky-bi-khinh-thuong-nhung-nam-chung-cu", label: "Thư ký bị khinh thường nhưng nắm chứng cứ" },
  { key: "tieu-thu-that-tro-ve", label: "Tiểu thư thật trở về" },
  { key: "thien-kim-gia-tu-cuu-minh", label: "Thiên kim giả tự cứu mình" },
  { key: "co-dau-thay-the-phan-don", label: "Cô dâu thay thế phản đòn" },
  { key: "co-dau-bo-tron-dung-luc", label: "Cô dâu bỏ trốn đúng lúc" },
  { key: "me-bim-am-tham-lat-an", label: "Mẹ bỉm âm thầm lật án" },
  { key: "me-don-than-lam-lai-su-nghiep", label: "Mẹ đơn thân làm lại sự nghiệp" },
  { key: "nguoi-vo-ky-don-ly-hon-khong-quay-dau", label: "Người vợ ký đơn ly hôn không quay đầu" },
  { key: "vo-cu-bien-mat-roi-tro-lai", label: "Vợ cũ biến mất rồi trở lại" },
  { key: "nu-ceo-bi-gia-dinh-ep-hon", label: "Nữ CEO bị gia đình ép hôn" },
  { key: "nha-thiet-ke-bi-dao-nhai", label: "Nhà thiết kế bị đạo nhái" },
  { key: "nu-dien-vien-bi-cuop-vai", label: "Nữ diễn viên bị cướp vai" },
  { key: "idol-het-thoi-tu-minh-oan", label: "Idol hết thời tự minh oan" },
  { key: "kol-bi-bao-luc-mang-phan-cong", label: "KOL bị bạo lực mạng phản công" },
  { key: "phong-vien-dieu-tra-sac-ben", label: "Phóng viên điều tra sắc bén" },
  { key: "bien-tap-vien-giu-bi-mat-lon", label: "Biên tập viên giữ bí mật lớn" },
  { key: "phien-dich-nghe-len-duoc-su-that", label: "Phiên dịch nghe lén được sự thật" },
  { key: "tiep-vien-hang-khong-che-giau-than-phan", label: "Tiếp viên hàng không che giấu thân phận" },
  { key: "quan-ly-khach-san-biet-qua-nhieu", label: "Quản lý khách sạn biết quá nhiều" },
  { key: "tham-tu-tu-nu-lanh-lung", label: "Thám tử tư nữ lạnh lùng" },
  { key: "ve-si-nu-bao-ve-nguoi-yeu-the", label: "Vệ sĩ nữ bảo vệ người yếu thế" },
  { key: "co-gai-que-bi-hao-mon-xem-thuong", label: "Cô gái quê bị hào môn xem thường" },
  { key: "nguoi-thua-ke-that-lac", label: "Người thừa kế thất lạc" },
  { key: "song-sinh-bi-trao-than-phan", label: "Song sinh bị tráo thân phận" },
  { key: "con-nuoi-bi-coi-la-quan-co", label: "Con nuôi bị coi là quân cờ" },
  { key: "nu-bac-si-khoa-san-giu-bi-mat-sinh-tu", label: "Nữ bác sĩ khoa sản giữ bí mật sinh tử" },
  { key: "me-mat-con-quyet-tim-su-that", label: "Mẹ mất con quyết tìm sự thật" },
  { key: "nguoi-phu-nu-mat-tri-nho-dan-nho-lai", label: "Người phụ nữ mất trí nhớ dần nhớ lại" },
  { key: "nguoi-tung-gia-chet-tro-ve", label: "Người từng giả chết trở về" },
  { key: "nu-chinh-bi-gai-lam-ac-nu", label: "Nữ chính bị gài làm ác nữ" },
  { key: "ac-nu-tinh-ngo-tu-cuu-danh-tieng", label: "Ác nữ tỉnh ngộ tự cứu danh tiếng" },
  { key: "nguoi-vo-ngheo-gia-than-phan", label: "Người vợ nghèo giả thân phận" },
  { key: "nhan-vien-nho-quay-lai-lam-sep", label: "Nhân viên nhỏ quay lại làm sếp" },
  { key: "dong-sang-lap-bi-phan-boi", label: "Đồng sáng lập bị phản bội" },
  { key: "co-dong-im-lang-doat-quyen", label: "Cổ đông im lặng đoạt quyền" },
  { key: "kiem-toan-vien-nhin-ra-lo-hong", label: "Kiểm toán viên nhìn ra lỗ hổng" },
  { key: "nhan-vien-ngan-hang-nam-giao-dich-la", label: "Nhân viên ngân hàng nắm giao dịch lạ" },
  { key: "nu-luat-su-gia-dinh-bao-ve-dua-tre", label: "Nữ luật sư gia đình bảo vệ đứa trẻ" },
  { key: "nguoi-me-mat-quyen-nuoi-con-phan-cong", label: "Người mẹ mất quyền nuôi con phản công" },
  { key: "co-giao-bi-phu-huynh-quyen-the-ep-toi", label: "Cô giáo bị phụ huynh quyền thế ép tội" },
  { key: "hieu-truong-tre-lat-lai-ho-so", label: "Hiệu trưởng trẻ lật lại hồ sơ" },
  { key: "nguoi-giup-viec-thong-minh-giu-bang-chung", label: "Người giúp việc thông minh giữ bằng chứng" },
  { key: "bao-mau-thay-camera-phong-tre", label: "Bảo mẫu thấy camera phòng trẻ" },
  { key: "y-ta-dem-biet-su-that", label: "Y tá đêm biết sự thật" },
  { key: "duoc-si-phat-hien-thuoc-bi-doi", label: "Dược sĩ phát hiện thuốc bị đổi" },
  { key: "chu-tiem-anh-luu-tam-hinh-cu", label: "Chủ tiệm ảnh lưu tấm hình cũ" },
  { key: "chu-quan-ca-phe-nghe-cuoc-hen-sai-nguoi", label: "Chủ quán cà phê nghe cuộc hẹn sai người" },
  { key: "nha-van-dung-cau-chuyen-de-phan-don", label: "Nhà văn dùng câu chuyện để phản đòn" },
  { key: "hoa-si-nhin-ra-buc-tranh-gia", label: "Họa sĩ nhìn ra bức tranh giả" },
  { key: "dau-bep-nu-bi-gia-toc-am-thuc-khinh-thuong", label: "Đầu bếp nữ bị gia tộc ẩm thực khinh thường" },
  { key: "nguoi-mau-bi-thay-vay-phut-cuoi", label: "Người mẫu bị thay váy phút cuối" },
  { key: "nha-thiet-ke-trang-suc-giu-tin-vat", label: "Nhà thiết kế trang sức giữ tín vật" },
  { key: "chuyen-vien-pr-xoay-chuyen-hot-search", label: "Chuyên viên PR xoay chuyển hot search" },
  { key: "quan-ly-nghe-si-chong-lung-am-tham", label: "Quản lý nghệ sĩ chống lưng âm thầm" },
  { key: "dao-dien-nu-bi-cuop-du-an", label: "Đạo diễn nữ bị cướp dự án" },
  { key: "nha-san-xuat-bi-boi-nho", label: "Nhà sản xuất bị bôi nhọ" },
  { key: "streamer-bi-cat-ghep-clip", label: "Streamer bị cắt ghép clip" },
  { key: "nguoi-phu-nu-tung-o-co-nhi-vien", label: "Người phụ nữ từng ở cô nhi viện" },
  { key: "co-gai-mang-tin-vat-gia-toc", label: "Cô gái mang tín vật gia tộc" },
  { key: "nu-chinh-co-hai-than-phan", label: "Nữ chính có hai thân phận" },
  { key: "ban-ngay-yeu-the-ban-dem-nam-quyen", label: "Ban ngày yếu thế ban đêm nắm quyền" },
  { key: "co-vo-hop-dong-khong-con-ngoan-ngoan", label: "Cô vợ hợp đồng không còn ngoan ngoãn" },
  { key: "hon-the-gia-bien-gia-thanh-that", label: "Hôn thê giả biến giả thành thật" },
  { key: "nguoi-xem-mat-bi-nham-danh-tinh", label: "Người xem mắt bị nhầm danh tính" },
  { key: "co-dau-lien-hon-tu-dat-dieu-kien", label: "Cô dâu liên hôn tự đặt điều kiện" },
  { key: "nguoi-phu-nu-bi-me-chong-ep-toi", label: "Người phụ nữ bị mẹ chồng ép tội" },
  { key: "chi-dau-bi-ca-nha-do-loi", label: "Chị dâu bị cả nhà đổ lỗi" },
  { key: "em-dau-im-lang-gom-sao-ke", label: "Em dâu im lặng gom sao kê" },
  { key: "con-dau-bi-xem-thuong-trong-tu-duong", label: "Con dâu bị xem thường trong từ đường" },
  { key: "nu-chinh-biet-dung-truyen-thong", label: "Nữ chính biết dùng truyền thông" },
  { key: "nu-chinh-biet-dung-phap-luat", label: "Nữ chính biết dùng pháp luật" },
  { key: "nu-chinh-biet-dung-tien-va-co-phan", label: "Nữ chính biết dùng tiền và cổ phần" },
  { key: "nu-chinh-biet-dung-nhan-chung", label: "Nữ chính biết dùng nhân chứng" },
  { key: "nu-chinh-khong-khoc-truoc-mat-ke-thu", label: "Nữ chính không khóc trước mặt kẻ thù" },
  { key: "nu-chinh-mem-mong-nhung-khong-tha-thu", label: "Nữ chính mềm mỏng nhưng không tha thứ" },
  { key: "nu-chinh-dam-bo-di-khi-con-yeu", label: "Nữ chính dám bỏ đi khi còn yêu" },
  { key: "nu-chinh-tra-thu-bang-su-that", label: "Nữ chính trả thù bằng sự thật" },
]
