import type { VietnameseProseRule } from './vietnameseProseQuality.js'

function normalizeEvidencePlace(input: string) {
  const value = String(input || '').trim().toLowerCase()
  if (!value) return 'túi áo'
  if (value.includes('lòng áo') || value.includes('ngực') || value.includes('trước ngực')) return 'túi áo'
  if (value.includes('tay áo')) return 'tay áo'
  if (value === 'tay' || value.includes('trong tay')) return 'lòng bàn tay'
  return input.trim()
}

export const userVietnameseProseReplacementRules: VietnameseProseRule[] = [
  {
    id: 'user-object-small-stone-template',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /(Tôi\s+(?:giữ|cầm|nắm))\s+([^.!?\n]{2,60})\s+như\s+một\s+viên\s+đá\s+nhỏ\s+trong\s+([^.!?\n]{2,50})/giu,
    replacement: (_match, captures) => {
      const object = captures[1]?.trim() || 'vật chứng đó'
      const place = normalizeEvidencePlace(captures[2] || '')
      return `Tôi giữ chặt ${object} trong ${place}, không để ai chạm vào`
    },
    message: 'Ẩn dụ vật chứng như “viên đá nhỏ” gượng; đổi thành hành động giữ vật chứng cụ thể.',
    genericSuggestion: 'Tôi giữ chặt [vật chứng] trong [túi áo/lòng bàn tay/túi xách], không để ai chạm vào.',
    examples: [
      {
        bad: 'Tôi giữ mẩu giấy như một viên đá nhỏ trong lòng áo.',
        good: 'Tôi giữ chặt mẩu giấy trong túi áo, không để ai chạm vào.',
      },
    ],
  },
  {
    id: 'user-speech-like-needle',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Lời\s+(?:nói|đó|ấy)\s+như\s+kim\s+châm\s+vào\s+([^.!?\n]{2,80})/giu,
    replacement: (_match, captures) => {
      const target = captures[0]?.trim() || 'tôi'
      return `Câu đó khiến vài người quay sang nhìn ${target}`
    },
    message: 'Ẩn dụ “lời nói như kim châm” sáo; đổi thành phản ứng cụ thể của người xung quanh.',
    genericSuggestion: 'Câu đó khiến [người xung quanh] quay sang nhìn [nhân vật] với thái độ cụ thể.',
    examples: [
      {
        bad: 'Lời nói như kim châm vào mặt tôi giữa đám đông.',
        good: 'Câu đó khiến vài phụ huynh quay sang nhìn tôi khó chịu.',
      },
    ],
  },
  {
    id: 'user-eyes-stuck-short-form',
    category: 'collocation',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Mắt\s+tôi\s+vẫn\s+dán\s+vào\s+([^.!?\n]{2,80})/giu,
    replacement: 'Tôi vẫn nhìn chằm chằm vào $1',
    message: 'Cụm “mắt tôi vẫn dán vào...” còn giọng AI/convert; đổi thành hành động nhìn cụ thể.',
    genericSuggestion: 'Tôi vẫn nhìn chằm chằm vào [vật/điểm cần chú ý].',
  },
  {
    id: 'user-crowded-like-beehive',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,60})\s+chật\s+như\s+tổ\s+ong\s+([^.!?\n]{0,50})/giu,
    replacement: (_match, captures) => {
      const place = captures[0]?.trim() || 'Nơi đó'
      const tail = captures[1]?.trim()
      return `${place} ${tail ? `${tail} ` : ''}chật kín người`.replace(/\s+/g, ' ').trim()
    },
    message: 'So sánh “chật như tổ ong” hơi AI; đổi thành mô tả trực tiếp.',
    genericSuggestion: '[Địa điểm] chật kín [người/khách/phụ huynh].',
    examples: [
      {
        bad: 'Cổng trường quốc tế chật như tổ ong buổi tan học.',
        good: 'Cổng trường quốc tế giờ tan học chật kín phụ huynh.',
      },
    ],
  },
  {
    id: 'user-warm-smell-collocation',
    category: 'collocation',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /tay\s+còn\s+ấm\s+mùi\s+([^,.!?\n]{2,40})/giu,
    replacement: 'trên người vẫn còn thoang thoảng mùi $1',
    message: 'Cụm “tay còn ấm mùi...” sai collocation; đổi thành mùi còn vương trên người/áo.',
    genericSuggestion: 'Trên áo/người [nhân vật] vẫn còn thoang thoảng mùi [mùi cụ thể].',
  },
  {
    id: 'user-public-opinion-hired',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,80})\s+trông\s+như\s+đã\s+thuê\s+được\s+cả\s+tiếng\s+nói\s+công\s+luận/giu,
    replacement: '$1 đứng giữa đám đông, vẻ mặt như thể mọi người đã đứng về phía mình',
    message: 'Cụm “thuê được cả tiếng nói công luận” nghe như bài phân tích; đổi thành phản ứng đám đông.',
    genericSuggestion: '[Nhân vật] đứng giữa đám đông, vẻ mặt như thể mọi người đã đứng về phía mình.',
  },
  {
    id: 'user-next-step-not-noisy-replace',
    category: 'slogan',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Bước\s+đi\s+tiếp\s+theo\s+sẽ\s+không\s+ồn\s+ào:\s*([^.!?\n]{2,160})/giu,
    replacement: 'Tôi không nói thêm. Trước mắt, tôi phải $1',
    message: 'Câu “Bước đi tiếp theo sẽ không ồn ào” giống slogan; đổi thành hành động trước mắt.',
    genericSuggestion: 'Tôi không nói thêm. Trước mắt, tôi phải [hành động cụ thể].',
  },
  {
    id: 'user-voice-wants-investigation',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Giọng\s+([^,.!?\n]{2,40})\s+muốn\s+lôi\s+kéo\s+một\s+cuộc\s+([^.!?\n]{2,80})/giu,
    replacement: '$1 nói lớn, rõ ràng muốn mọi người ép bên liên quan kiểm tra ngay tại chỗ',
    message: 'Câu “giọng muốn lôi kéo...” là diễn giải AI; đổi thành hành động nói lớn và tác động cụ thể.',
    genericSuggestion: '[Nhân vật] nói lớn, rõ ràng muốn mọi người ép [bên liên quan] kiểm tra ngay tại chỗ.',
  },
  // Rule mới từ 3 truyện test: file âm thanh / phiếu gửi đồ / video 7 giây
  {
    id: 'user-object-as-living-thing',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Tôi\s+giữ\s+([^.!?\n]{2,70})\s+như\s+một\s+thứ\s+còn\s+sống/giu,
    replacement: 'Tôi giữ chặt $1, không để ai chạm vào',
    message: 'Ẩn dụ “giữ như một thứ còn sống” làm vật chứng bị văn chương hóa; đổi thành hành động giữ cụ thể.',
    genericSuggestion: 'Tôi giữ chặt [vật chứng], không để ai chạm vào.',
  },
  {
    id: 'user-thin-cold-smile',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /nụ\s+cười\s+(?:của\s+[^,.!?\n]{1,30}\s+)?(?:mỏng|mảnh)\s+và\s+lạnh/giu,
    replacement: 'nụ cười lạnh nhạt',
    message: 'Cụm “nụ cười mỏng/mảnh và lạnh” sáo, đổi thành mô tả gọn hơn.',
  },
  {
    id: 'user-pressure-not-abstract',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Áp\s+lực\s+không\s+phải\s+là\s+điều\s+trừu\s+tượng\s*[—-]\s*nó\s+nằm\s+([^.!?\n]{2,140})/giu,
    replacement: 'Áp lực nằm ngay $1',
    message: 'Câu “áp lực không phải là điều trừu tượng” là telling AI; bỏ phần giải thích và giữ chi tiết cụ thể.',
    genericSuggestion: 'Viết trực tiếp áp lực nằm ở đâu: màn hình, số người xem, ánh mắt, giấy tờ, tin nhắn.',
  },
  {
    id: 'user-voice-as-bargain',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Giọng\s+([^.!?\n]{0,40})\s+như\s+đặt\s+một\s+giao\s+kèo/giu,
    replacement: '$1 nói như đang ép tôi phải chọn ngay',
    message: 'Ẩn dụ “giọng như đặt một giao kèo” hơi AI; đổi thành ý ép lựa chọn cụ thể.',
  },
  {
    id: 'user-heart-running-wild',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Tim\s+tôi\s+như\s+lồng\s+lộn/giu,
    replacement: 'Tim tôi đập mạnh',
    message: 'Cụm “tim như lồng lộn” hơi quá đà; đổi thành phản ứng cơ thể tự nhiên hơn.',
  },
  {
    id: 'user-question-stone-air',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /Câu\s+hỏi\s+như\s+đặt\s+cục\s+đá\s+xuống\s+giữa\s+không\s+khí\.?,?/giu,
    replacement: 'Câu hỏi đó khiến vài người im lại.',
    message: 'Ẩn dụ “cục đá giữa không khí” gượng; đổi thành phản ứng của người xung quanh.',
  },
  {
    id: 'user-side-person-enters-game',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Người\s+tưởng\s+ở\s+(?:ngoài\s+)?lề\s+đã\s+bước\s+vào\s+giữa\s+ván\s+bài/giu,
    replacement: 'Người tưởng không liên quan lúc này lại xuất hiện đúng chỗ',
    message: 'Cụm “bước vào giữa ván bài” sân khấu hóa; đổi thành tình huống cụ thể.',
  },
  {
    id: 'user-small-truth-opens',
    category: 'slogan',
    severity: 'medium',
    mode: 'replace',
    pattern: /Một\s+mảnh\s+nhỏ\s+của\s+sự\s+thật\s+hé\s+ra\.?,?/giu,
    replacement: 'Tôi bắt đầu hiểu có người khác đứng sau chuyện này.',
    message: 'Câu “một mảnh nhỏ của sự thật hé ra” giống tổng kết AI; đổi thành nhận định cụ thể.',
  },
  {
    id: 'user-words-open-light-gap',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Lời\s+([^.!?\n]{0,35})\s+như\s+mở\s+một\s+khe\s+sáng/giu,
    replacement: 'Lời $1 khiến tôi chú ý',
    message: 'Ẩn dụ “mở một khe sáng” hơi AI; đổi thành phản ứng chú ý cụ thể.',
  },
  {
    id: 'user-pull-evidence-to-light',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /(?:đủ\s+để\s+)?kéo\s+([^.!?\n]{2,80})\s+vào\s+ánh\s+sáng/giu,
    replacement: 'giúp tôi kiểm tra $1 trước mặt mọi người',
    message: 'Cụm “kéo ... vào ánh sáng” sáo; đổi thành hành động kiểm tra cụ thể.',
    genericSuggestion: 'giúp tôi kiểm tra [vật chứng/chi tiết] trước mặt mọi người.',
  },
  {
    id: 'user-not-win-but-gap',
    category: 'slogan',
    severity: 'medium',
    mode: 'replace',
    pattern: /Lần\s+này\s+chúng\s+tôi\s+chưa\s+thắng,\s*nhưng\s+đã\s+tìm\s+được\s+khe\s+hở\s+để\s+bám\s+vào\.?,?/giu,
    replacement: 'Tôi chưa thắng. Nhưng ít nhất, họ không thể bắt tôi nhận lỗi ngay lúc này.',
    message: 'Câu “chưa thắng nhưng có khe hở” là slogan AI; đổi thành lợi thế cụ thể trong cảnh.',
  },
  {
    id: 'user-background-sound-chaos',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,120})\s+thành\s+một\s+thứ\s+nền\s+âm\s+hỗn\s+độn/giu,
    replacement: '$1 trộn vào nhau',
    message: 'Cụm “nền âm hỗn độn” hơi làm văn; đổi thành mô tả trực tiếp.',
  },
  {
    id: 'user-voice-string-heart',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /Giọng\s+con\s+nhỏ,\s*run,\s*kéo\s+một\s+sợi\s+gì\s+đó\s+vào\s+tim\s+tôi\.?,?/giu,
    replacement: 'Giọng con nhỏ và run. Tôi nghe mà nghẹn lại.',
    message: 'Ẩn dụ “kéo một sợi gì đó vào tim” gượng; đổi thành phản ứng cảm xúc trực tiếp.',
  },
  {
    id: 'user-file-becomes-trap',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,60})\s+không\s+còn\s+là\s+file,\s*nó\s+thành\s+tấm\s+bẫy/giu,
    replacement: '$1 không còn là một đoạn file bình thường nữa. Nó đã bị dùng để gài bẫy tôi',
    message: 'Cụm “file thành tấm bẫy” hơi poster; đổi thành câu rõ nghĩa hơn.',
  },
  {
    id: 'user-eyes-this-is-their-yard',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Ánh\s+mắt\s+anh\s+nói\s+rõ:\s*đây\s+là\s+sân\s+của\s+họ/giu,
    replacement: 'Cách anh ta nhìn quanh khiến tôi hiểu nơi này đã được họ chuẩn bị từ trước',
    message: 'Câu “ánh mắt nói rõ: đây là sân của họ” sân khấu hóa; đổi thành nhận biết cụ thể.',
  },
  {
    id: 'user-switch-flipped',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Câu\s+đó\s+như\s+bật\s+công\s+tắc\.?,?/giu,
    replacement: 'Sau câu đó, đám phóng viên bắt đầu ồn lên.',
    message: 'Ẩn dụ “bật công tắc” dễ AI; đổi thành phản ứng cụ thể.',
  },
  {
    id: 'user-black-streak-light',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,80})\s+theo\s+tôi\s+như\s+một\s+vệt\s+đen\s+giữa\s+ánh\s+sáng/giu,
    replacement: '$1 vẫn ám trong đầu tôi',
    message: 'Ẩn dụ “vệt đen giữa ánh sáng” văn hoa; đổi thành cảm giác nhớ/ám ảnh rõ hơn.',
  },
  {
    id: 'user-more-than-voice',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /người\s+ta\s+sẽ\s+lấy\s+đi\s+nhiều\s+hơn\s+tiếng\s+nói\s+của\s+mình/giu,
    replacement: 'họ sẽ kéo thêm người vô tội vào chuyện này',
    message: 'Câu “lấy đi nhiều hơn tiếng nói” trừu tượng; đổi thành hậu quả cụ thể.',
  },
  {
    id: 'user-countdown-hours-starts',
    category: 'slogan',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /(\d+|mười\s+hai|mười\s+lăm|hai\s+mươi\s+bốn)\s+tiếng\s+bắt\s+đầu\s+đếm\s+ngược/giu,
    replacement: 'Tôi chỉ còn $1 tiếng để xác minh',
    message: 'Câu “bắt đầu đếm ngược” giống slogan; đổi thành thời hạn cụ thể của nhân vật.',
  },
  {
    id: 'user-this-is-only-beginning',
    category: 'slogan',
    severity: 'medium',
    mode: 'replace',
    pattern: /Đây\s+mới\s+chỉ\s+là\s+bước\s+đầu\.?,?/giu,
    replacement: 'Tôi biết chuyện này chưa dừng ở đây.',
    message: 'Câu “đây mới chỉ là bước đầu” là slogan quen thuộc; đổi thành nhận định đời hơn.',
  },
  {
    id: 'user-decision-changed-attitude',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'replace',
    pattern: /Quyết\s+định\s+đó\s+thay\s+đổi\s+thái\s+độ\s+quanh\s+tôi\.?,?/giu,
    replacement: 'Sau câu đó, vài người nhìn tôi khác hẳn.',
    message: 'Câu “quyết định thay đổi thái độ” là telling; đổi thành phản ứng người xung quanh.',
  },
  {
    id: 'user-power-still-hanging',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Quyền\s+lực\s+của\s+([^.!?\n]{1,40})\s+vẫn\s+treo\s+đó/giu,
    replacement: '$1 vẫn còn cách gây sức ép',
    message: 'Cụm “quyền lực vẫn treo đó” trừu tượng; đổi thành sức ép cụ thể.',
  },
  {
    id: 'user-clue-out-of-dark',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,80})\s+như\s+dấu\s+vết\s+vừa\s+ló\s+ra\s+khỏi\s+tối/giu,
    replacement: '$1 là chi tiết tôi cần kiểm tra tiếp',
    message: 'Ẩn dụ “ló ra khỏi tối” văn hoa; đổi thành hành động kiểm tra tiếp.',
  },
  {
    id: 'user-card-as-promise',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /đặt\s+lên\s+lòng\s+bàn\s+tay\s+như\s+một\s+lời\s+hứa/giu,
    replacement: 'giữ chặt trong lòng bàn tay',
    message: 'Cụm “đặt lên lòng bàn tay như lời hứa” văn hoa; đổi thành hành động giữ cụ thể.',
  },

  // Rule mới từ truyện test: Mảnh vải mẫu / Bản hợp đồng
  {
    id: 'user-flickering-fluorescent-light',
    category: 'collocation',
    severity: 'low',
    mode: 'replace',
    pattern: /đèn\s+huỳnh\s+quang\s+bật\s+bật/giu,
    replacement: 'đèn huỳnh quang hơi nhấp nháy',
    message: 'Cụm “đèn huỳnh quang bật bật” sai tai; đổi thành mô tả tự nhiên hơn.',
  },
  {
    id: 'user-fabric-idea-waits-stage',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'replace',
    pattern: /mỗi\s+tấm\s+là\s+một\s+ý\s+tưởng\s+chờ\s+ra\s+sân\s+khấu/giu,
    replacement: 'mỗi tấm là một mẫu chuẩn bị đưa vào buổi trình diễn',
    message: 'Câu “ý tưởng chờ ra sân khấu” hơi văn hoa; đổi thành chức năng cụ thể của mẫu vải.',
  },
  {
    id: 'user-look-like-prepared-file',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /([^.!?\n]{1,80})\s+nhìn\s+tôi\s+như\s+đọc\s+một\s+hồ\s+sơ\s+đã\s+soạn\s+sẵn/giu,
    replacement: '$1 nhìn tôi như đã chuẩn bị sẵn kết luận',
    message: 'Ẩn dụ “đọc một hồ sơ đã soạn sẵn” hơi AI; đổi thành thái độ đã kết luận sẵn.',
    genericSuggestion: '[Nhân vật] nhìn tôi như đã chuẩn bị sẵn kết luận.',
  },
  {
    id: 'user-words-sucked-into-throat',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /lời\s+([^.!?\n]{0,40})\s+như\s+bị\s+hút\s+vào\s+cổ\s+họng/giu,
    replacement: 'giọng $1 nhỏ đến mức gần như không nghe rõ',
    message: 'Cụm “lời như bị hút vào cổ họng” gượng; đổi thành âm lượng/giọng nói cụ thể.',
  },
  {
    id: 'user-contract-as-hammer',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /nhắc\s+tới\s+([^.!?\n]{2,50})\s+như\s+một\s+cây\s+búa/giu,
    replacement: 'nhắc tới $1 để ép mọi người im lại',
    message: 'Ẩn dụ “như một cây búa” gượng; đổi thành tác dụng gây sức ép trong cảnh.',
  },
  {
    id: 'user-public-pressure-changes-tone',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Áp\s+lực\s+công\s+chúng\s+bắt\s+đầu\s+chuyển\s+tông/giu,
    replacement: 'Vài người bắt đầu giơ điện thoại lên quay, tiếng xì xào cũng lớn hơn',
    message: 'Câu “áp lực công chúng chuyển tông” là telling; đổi thành hành động cụ thể của đám đông.',
  },
  {
    id: 'user-phrase-like-lid-closing',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Câu\s+["“]([^"”\n]{2,80})["”]\s+như\s+cái\s+nắp\s+đóng\s+xuống/giu,
    replacement: 'Sau câu “$1”, mọi người hiểu quyết định tạm thời đã được đưa ra',
    message: 'Ẩn dụ “cái nắp đóng xuống” văn hoa; đổi thành hệ quả cụ thể sau câu nói.',
  },
  {
    id: 'user-eye-saw-evidence',
    category: 'collocation',
    severity: 'medium',
    mode: 'replace',
    pattern: /con\s+mắt\s+đã\s+thấy/giu,
    replacement: 'tôi đã nhìn thấy',
    message: 'Cụm “con mắt đã thấy” sai tai; đổi thành chủ thể người kể trực tiếp.',
  },
  {
    id: 'user-ear-heart-buzzing',
    category: 'collocation',
    severity: 'medium',
    mode: 'replace',
    pattern: /Tim\s+tôi\s+lùng\s+bùng/giu,
    replacement: 'Tai tôi ù đi',
    message: 'Cụm “tim tôi lùng bùng” sai collocation; đổi thành phản ứng cơ thể tự nhiên hơn.',
  },
  {
    id: 'user-clip-valuable-thing-under-shirt',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /như\s+kẹp\s+một\s+mảnh\s+đồ\s+quý\s+dưới\s+áo/giu,
    replacement: 'giữ thật chặt trong lòng bàn tay',
    message: 'Cụm “mảnh đồ quý dưới áo” gượng; đổi thành hành động giữ vật chứng cụ thể.',
  },
  {
    id: 'user-voice-as-stamp',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /giọng\s+([^.!?\n]{0,30})\s+như\s+đóng\s+dấu/giu,
    replacement: 'giọng $1 dứt khoát',
    message: 'Ẩn dụ “giọng như đóng dấu” hơi convert/AI; đổi thành sắc thái giọng cụ thể.',
  },
  {
    id: 'user-close-rebuttal-path',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /đóng\s+chặt\s+một\s+lối\s+phản\s+bác/giu,
    replacement: 'chặn trước mọi lời phản bác',
    message: 'Cụm “đóng chặt một lối phản bác” gượng; đổi thành ý rõ hơn.',
  },
  {
    id: 'user-eyes-shifting',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Tôi\s+cảm\s+nhận\s+ánh\s+mắt\s+dịch\s+chuyển/giu,
    replacement: 'Tôi thấy mọi người bắt đầu quay sang nhìn nhau',
    message: 'Câu “cảm nhận ánh mắt dịch chuyển” trừu tượng; đổi thành phản ứng nhìn thấy được.',
  },
  {
    id: 'user-evidence-speaks-that',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,60})\s+nói\s+rằng\s+ai\s+đó\s+đã\s+([^.!?\n]{2,100})/giu,
    replacement: '$1 cho thấy có người đã $2',
    message: 'Không để vật chứng “nói rằng”; đổi thành “cho thấy” hoặc suy luận của nhân vật.',
    genericSuggestion: '[Vật chứng] cho thấy có người đã [hành động cụ thể].',
  },
  {
    id: 'user-evidence-asks-what-next',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /Dấu\s+mực\s+lệch\s+đã\s+xuất\s+hiện\.\s*Nó\s+hỏi\s+tôi\s+phải\s+làm\s+gì\s+tiếp\s+theo\.?/giu,
    replacement: 'Dấu mực lệch nằm ngay trước mắt. Tôi không thể ký khi chưa biết ai đã sửa trang này.',
    message: 'Vật chứng không “hỏi”; đổi thành quyết định cụ thể của nhân vật.',
  },
  {
    id: 'user-fire-awake-inside',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /trong\s+lòng\s+lửa\s+tỉnh/giu,
    replacement: 'tôi cố giữ tỉnh táo',
    message: 'Cụm “trong lòng lửa tỉnh” rất gượng/AI; đổi thành trạng thái cụ thể.',
  },
  {
    id: 'user-eyes-say-usb',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /ánh\s+mắt\s+cô\s+nói\s+["“]USB["”]/giu,
    replacement: 'cô liếc xuống túi áo tôi, ra hiệu về chiếc USB',
    message: 'Câu “ánh mắt cô nói USB” sai tự nhiên; đổi thành cử chỉ cụ thể.',
  },
  {
    id: 'user-power-not-only-seal',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /quyền\s+lực\s+không\s+chỉ\s+nằm\s+trên\s+con\s+dấu/giu,
    replacement: 'chỉ cần giữ được bản gốc và chứng cứ, họ chưa thể ép tôi ký ngay',
    message: 'Cụm “quyền lực nằm trên con dấu” trừu tượng; đổi thành lợi thế cụ thể.',
  },
  {
    id: 'user-door-like-appointment',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Cửa\s+([^.!?\n]{0,50})\s+đóng\s+lại\s+sau\s+lưng\s+như\s+một\s+lời\s+hẹn/giu,
    replacement: 'Cửa $1 khép lại sau lưng. Tôi biết chuyện chưa dừng ở đây',
    message: 'Ẩn dụ “cửa như một lời hẹn” văn hoa; đổi thành nhận định cụ thể.',
  },
  {
    id: 'user-mother-must-be-awake',
    category: 'collocation',
    severity: 'high',
    mode: 'replace',
    pattern: /Mẹ\s+phải\s+tỉnh/giu,
    replacement: 'Tôi phải tỉnh táo',
    message: 'Câu “Mẹ phải tỉnh” gượng; đổi thành lời tự nhắc tự nhiên hơn.',
  },
  {
    id: 'user-follow-clue-to-end',
    category: 'slogan',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Tôi\s+có\s+một\s+manh\s+mối,\s*và\s+sẽ\s+theo\s+nó\s+tới\s+cùng\.?/giu,
    replacement: 'Tôi giữ chặt vật chứng trong túi. Trước hết, tôi phải tìm ra người đã động tay vào nó.',
    message: 'Câu “theo manh mối tới cùng” là slogan; đổi thành hành động tiếp theo cụ thể.',
  },
  {
    id: 'user-go-find-truth-ending',
    category: 'slogan',
    severity: 'medium',
    mode: 'replace',
    pattern: /Tôi\s+đi\s+theo\s+hướng\s+khác:\s*đi\s+tìm\s+sự\s+thật\.?/giu,
    replacement: 'Tôi kiểm tra lại USB trong balo rồi gọi cho trợ lý lần nữa.',
    message: 'Câu “đi tìm sự thật” là slogan; đổi thành hành động cụ thể.',
  },

  // Rule mới từ feedback prose: câu tối nghĩa / metaphor AI / collocation sai
  // Đã generic hóa: không gắn với tên nhân vật, motif, vật chứng hay bối cảnh cụ thể.
  {
    id: 'user-eyes-thrown-to-place',
    category: 'collocation',
    severity: 'high',
    mode: 'template-replace',
    pattern: /Mọi\s+ánh\s+mắt\s+quăng\s+sang\s+([^.!?\n]{2,80})/giu,
    replacement: 'Mọi ánh mắt lập tức đổ dồn về $1',
    message: '“Ánh mắt quăng sang” sai collocation; đổi thành “đổ dồn về”.',
    genericSuggestion: 'Dùng “ánh mắt đổ dồn về...” hoặc “mọi người quay sang nhìn...”.',
  },
  {
    id: 'user-noose-pressure-room-typo',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /Áp\s+lực\s+đè\s+lên\s+phòng,\s*như\s+một\s+lòng\s+vòng\s+siết\s+vào\.?/giu,
    replacement: 'Áp lực đè xuống căn phòng, khiến cả tiếng thở cũng nặng hơn.',
    message: 'Câu “lòng vòng siết vào” sai chữ/tối nghĩa; đổi thành áp lực cụ thể trong phòng.',
  },
  {
    id: 'user-rock-to-hold-metaphor',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /như\s+tìm\s+một\s+hòn\s+đá\s+bám/giu,
    replacement: 'như đang chờ một câu chắc chắn',
    message: 'Ẩn dụ “hòn đá bám” gượng và tối nghĩa; đổi thành phản ứng mong chờ cụ thể.',
  },
  {
    id: 'user-knife-closing-door-metaphor',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /lời\s+đó\s+giống\s+như\s+một\s+con\s+dao\s+khép\s+lại\s+một\s+cánh\s+cửa/giu,
    replacement: 'lời đó khiến tình thế trước mắt càng khó xoay chuyển',
    message: 'Ẩn dụ “con dao khép lại cánh cửa” chồng hình ảnh, nghe AI; đổi thành hậu quả cụ thể.',
  },
  {
    id: 'user-name-placed-on-paper',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /để\s+vài\s+chiếc\s+tên\s+bị\s+đặt\s+trên\s+giấy/giu,
    replacement: 'để những cái tên liên quan không thể lẩn đi',
    message: '“Vài chiếc tên bị đặt trên giấy” sai tai và tối nghĩa; đổi thành ý truy trách nhiệm rõ hơn.',
  },
  {
    id: 'user-name-like-stone-hit-face',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Cái\s+tên\s+([^.!?\n]{1,40})\s+như\s+một\s+viên\s+đá\s+ném\s+vào\s+mặt\s+tôi/giu,
    replacement: 'Cái tên $1 khiến tôi khựng lại',
    message: 'Ẩn dụ “viên đá ném vào mặt” nặng và lộ AI; đổi thành phản ứng trực tiếp.',
  },
  {
    id: 'user-printed-ink-on-ticket',
    category: 'collocation',
    severity: 'high',
    mode: 'replace',
    pattern: /Trên\s+phiếu,\s*cái\s+mực\s+in\s+số\s+thứ\s+tự/giu,
    replacement: 'Trên phiếu có số thứ tự',
    message: '“Cái mực in số thứ tự” sai tiếng Việt; đổi thành thông tin trên phiếu.',
  },
  {
    id: 'user-item-picked-up-bad-subject',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /Gã\s+nhận\s+đồ\s+đã\s+có\s+người\s+tới\s+lấy\s+rồi,\s*không\s+phải\s+lễ\s+tân/giu,
    replacement: 'Món đồ đã có người tới lấy rồi, không qua quầy lễ tân',
    message: 'Câu sai chủ ngữ: “gã nhận đồ đã có người tới lấy” tối nghĩa; đổi thành vật/việc cụ thể.',
  },
  {
    id: 'user-cheeks-swell-breathe',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /Tôi\s+thấy\s+phồng\s+má,\s*thở\s+sâu/giu,
    replacement: 'Tôi mím môi, hít sâu một hơi',
    message: '“Tôi thấy phồng má” là lỗi diễn đạt; đổi thành phản ứng cơ thể tự nhiên.',
  },
  {
    id: 'user-auction-hammer-typo',
    category: 'technical_term',
    severity: 'high',
    mode: 'replace',
    pattern: /lễ\s+cứa\s+búa/giu,
    replacement: 'lượt gõ búa',
    message: 'Sửa typo “cứa búa” thành “lượt gõ búa”.',
  },
  {
    id: 'user-story-flashes-up',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /thái\s+độ\s+đủ\s+làm\s+mọi\s+câu\s+chuyện\s+lóe\s+lên/giu,
    replacement: 'thái độ của người đó đủ khiến cả phòng im xuống',
    message: '“Mọi câu chuyện lóe lên” tối nghĩa; đổi thành phản ứng cụ thể của không gian/đám đông.',
  },
  {
    id: 'user-cold-voice-sharp-ear',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /giọng\s+([^.!?\n]{0,40})\s+đủ\s+lạnh\s+để\s+ai\s+nghe\s+cũng\s+thấy\s+chói\s+tai/giu,
    replacement: 'giọng $1 lạnh đến mức cả phòng im đi',
    message: '“Lạnh” và “chói tai” lệch cảm giác; đổi thành phản ứng nghe tự nhiên hơn.',
  },
  {
    id: 'user-thing-during-childcare',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /đó\s+là\s+thứ\s+nằm\s+trong\s+lúc\s+tôi\s+trông\s+trẻ/giu,
    replacement: 'khi đó tôi còn đang bận việc khác, nên chỉ kịp ghi nhớ chi tiết ấy',
    message: '“Thứ nằm trong lúc tôi...” tối nghĩa; đổi thành quan hệ thời điểm rõ hơn.',
  },
  {
    id: 'user-small-sound-inside-heart',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Trong\s+lòng\s+tôi\s+thấy\s+một\s+tiếng\s+lách\s+cách/giu,
    replacement: 'Trong đầu tôi vang lên một tiếng lách cách',
    message: '“Trong lòng tôi thấy một tiếng...” sai giác quan; đổi thành cảm giác trong đầu.',
  },
  {
    id: 'user-sentence-like-knife-carved',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Câu\s+nói\s+dở\s+dang\s+như\s+mũi\s+dao\s+khắc\s+vào\s+tôi/giu,
    replacement: 'Câu nói dở dang khiến tôi nghẹn lại',
    message: 'Ẩn dụ “mũi dao khắc vào tôi” hơi AI; đổi thành phản ứng cảm xúc cụ thể.',
  },

]

export const userVietnameseProseWarningRules: VietnameseProseRule[] = [
  {
    id: 'user-warning-too-many-toi-openings',
    category: 'unclear_sentence',
    severity: 'low',
    mode: 'warning',
    pattern: /(?:^|\n)(?:Tôi\s+[^.!?\n]+[.!?]\s*){3,}/g,
    message: 'Nhiều câu liên tiếp bắt đầu bằng “Tôi”, dễ làm nhịp văn đều và máy.',
    genericSuggestion: 'Đổi một vài câu sang mở đầu bằng hành động, bối cảnh, hoặc phản ứng của người khác.',
  },
  {
    id: 'user-warning-administrative-dialogue',
    category: 'dialogue_role',
    severity: 'low',
    mode: 'warning',
    pattern: /triệu tập họp phụ huynh khẩn|ở lại để làm rõ|xử lý nghiêm/gi,
    message: 'Một số câu thoại hơi hành chính/sạch quá, nên làm đời hơn theo vai nói.',
    genericSuggestion: 'Thêm vai xưng hô cụ thể: “Mọi người bình tĩnh”, “phiền cô ở lại để đối chiếu...”, “nhà trường sẽ kiểm tra ngay”.',
  },
  {
    id: 'user-warning-evidence-as-heavy-object',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'warning',
    pattern: /như\s+một\s+(?:viên\s+đá|hòn\s+đá|khối\s+đá)/gi,
    message: 'So sánh vật chứng/cảm xúc với đá thường làm câu nặng và AI.',
    genericSuggestion: 'Đổi thành hành động cụ thể: giữ chặt, cất vào túi, đặt lên bàn, không để ai chạm vào.',
  },
  {
    id: 'user-warning-showbiz-poster-metaphors',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'warning',
    pattern: /ván\s+bài|vệt\s+đen\s+giữa\s+ánh\s+sáng|tấm\s+bẫy|bật\s+công\s+tắc|cục\s+đá\s+xuống\s+giữa\s+không\s+khí/giu,
    message: 'Cụm ẩn dụ kiểu poster/sân khấu hóa còn mùi AI.',
    genericSuggestion: 'Đổi thành hành động hoặc phản ứng cụ thể: ai im lại, ai nhìn sang, ai cầm giấy, ai bước vào.',
  },
  {
    id: 'user-warning-truth-light-metaphor',
    category: 'slogan',
    severity: 'medium',
    mode: 'warning',
    pattern: /sự\s+thật\s+hé\s+ra|kéo\s+[^.!?\n]{2,80}\s+vào\s+ánh\s+sáng|khe\s+hở\s+để\s+bám\s+vào/giu,
    message: 'Cụm “sự thật hé ra/kéo vào ánh sáng/khe hở” là câu tổng kết AI.',
    genericSuggestion: 'Viết cụ thể nhân vật phát hiện gì, giữ vật chứng gì, sẽ hỏi ai hoặc kiểm tra ở đâu.',
  },
  {
    id: 'user-warning-countdown-ending',
    category: 'slogan',
    severity: 'medium',
    mode: 'warning',
    pattern: /bắt\s+đầu\s+đếm\s+ngược|đây\s+mới\s+chỉ\s+là\s+bước\s+đầu|chuyện\s+này\s+chưa\s+dừng\s+ở\s+đây/giu,
    message: 'Câu kết kiểu countdown/bước đầu dễ thành slogan.',
    genericSuggestion: 'Kết bằng dữ kiện cụ thể: tin nhắn, người xuất hiện, vật chứng mới, thời hạn rõ, hoặc hành động tiếp theo.',
  },

  {
    id: 'user-warning-person-waiting-miracle',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'warning',
    pattern: /giống\s+người\s+đang\s+chờ\s+một\s+phép\s+lạ/giu,
    message: 'Cụm “chờ một phép lạ” hơi sáo; có thể giữ nếu hợp nhịp truyện mạng.',
    genericSuggestion: 'Nếu muốn sửa, đổi thành hành động cụ thể: nắm chặt túi, cúi đầu, nhìn người đối diện, không dám nói tiếp.',
  },
  {
    id: 'user-warning-background-sound-stops',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'warning',
    pattern: /Tiếng\s+[^.!?\n]{1,40}\s+như\s+cũng\s+dừng/giu,
    message: 'Câu “âm thanh như cũng dừng” là thủ pháp khá cũ; chỉ nên dùng ít.',
    genericSuggestion: 'Có thể đổi thành phản ứng người trong phòng: ai im lại, ai đặt ly xuống, ai quay sang nhìn.',
  },
  {
    id: 'user-warning-final-not-win-yet',
    category: 'slogan',
    severity: 'medium',
    mode: 'warning',
    pattern: /Tôi\s+không\s+thắng\s+ngay|Không\s+ai\s+thắng\s+hoàn\s+toàn|chưa\s+đủ,\s*nhưng\s+ít\s+nhất/giu,
    message: 'Câu tổng kết kiểu “chưa thắng nhưng...” dễ lộ AI nếu dùng nhiều.',
    genericSuggestion: 'Kết bằng vật chứng/hành động cụ thể: cất giấy vào túi, gọi một người, mở camera, hoặc đi tới địa điểm tiếp theo.',
  },


]
