import type { VietnameseProseRule } from './vietnameseProseQuality.js'

function normalizeEvidencePlace(input: string) {
  const value = String(input || '').trim().toLowerCase()
  if (!value) return 'túi áo'
  if (value.includes('lòng áo') || value.includes('ngực') || value.includes('trước ngực')) return 'túi áo'
  if (value.includes('tay áo')) return 'tay áo'
  if (value === 'tay' || value.includes('trong tay')) return 'lòng bàn tay'
  return input.trim()
}

export const userVietnameseProseReplacementRules: VietnameseProseRule[] = [
  {
    id: 'user-object-small-stone-template',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /(Tôi\s+(?:giữ|cầm|nắm))\s+([^.!?\n]{2,60})\s+như\s+một\s+viên\s+đá\s+nhỏ\s+trong\s+([^.!?\n]{2,50})/giu,
    replacement: (_match, captures) => {
      const object = captures[1]?.trim() || 'vật chứng đó'
      const place = normalizeEvidencePlace(captures[2] || '')
      return `Tôi giữ chặt ${object} trong ${place}, không để ai chạm vào`
    },
    message: 'Ẩn dụ vật chứng như “viên đá nhỏ” gượng; đổi thành hành động giữ vật chứng cụ thể.',
    genericSuggestion: 'Tôi giữ chặt [vật chứng] trong [túi áo/lòng bàn tay/túi xách], không để ai chạm vào.',
    examples: [
      {
        bad: 'Tôi giữ mẩu giấy như một viên đá nhỏ trong lòng áo.',
        good: 'Tôi giữ chặt mẩu giấy trong túi áo, không để ai chạm vào.',
      },
    ],
  },
  {
    id: 'user-speech-like-needle',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Lời\s+(?:nói|đó|ấy)\s+như\s+kim\s+châm\s+vào\s+([^.!?\n]{2,80})/giu,
    replacement: (_match, captures) => {
      const target = captures[0]?.trim() || 'tôi'
      return `Câu đó khiến vài người quay sang nhìn ${target}`
    },
    message: 'Ẩn dụ “lời nói như kim châm” sáo; đổi thành phản ứng cụ thể của người xung quanh.',
    genericSuggestion: 'Câu đó khiến [người xung quanh] quay sang nhìn [nhân vật] với thái độ cụ thể.',
    examples: [
      {
        bad: 'Lời nói như kim châm vào mặt tôi giữa đám đông.',
        good: 'Câu đó khiến vài phụ huynh quay sang nhìn tôi khó chịu.',
      },
    ],
  },
  {
    id: 'user-eyes-stuck-short-form',
    category: 'collocation',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Mắt\s+tôi\s+vẫn\s+dán\s+vào\s+([^.!?\n]{2,80})/giu,
    replacement: 'Tôi vẫn nhìn chằm chằm vào $1',
    message: 'Cụm “mắt tôi vẫn dán vào...” còn giọng AI/convert; đổi thành hành động nhìn cụ thể.',
    genericSuggestion: 'Tôi vẫn nhìn chằm chằm vào [vật/điểm cần chú ý].',
  },
  {
    id: 'user-crowded-like-beehive',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,60})\s+chật\s+như\s+tổ\s+ong\s+([^.!?\n]{0,50})/giu,
    replacement: (_match, captures) => {
      const place = captures[0]?.trim() || 'Nơi đó'
      const tail = captures[1]?.trim()
      return `${place} ${tail ? `${tail} ` : ''}chật kín người`.replace(/\s+/g, ' ').trim()
    },
    message: 'So sánh “chật như tổ ong” hơi AI; đổi thành mô tả trực tiếp.',
    genericSuggestion: '[Địa điểm] chật kín [người/khách/phụ huynh].',
    examples: [
      {
        bad: 'Cổng trường quốc tế chật như tổ ong buổi tan học.',
        good: 'Cổng trường quốc tế giờ tan học chật kín phụ huynh.',
      },
    ],
  },
  {
    id: 'user-warm-smell-collocation',
    category: 'collocation',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /tay\s+còn\s+ấm\s+mùi\s+([^,.!?\n]{2,40})/giu,
    replacement: 'trên người vẫn còn thoang thoảng mùi $1',
    message: 'Cụm “tay còn ấm mùi...” sai collocation; đổi thành mùi còn vương trên người/áo.',
    genericSuggestion: 'Trên áo/người [nhân vật] vẫn còn thoang thoảng mùi [mùi cụ thể].',
  },
  {
    id: 'user-public-opinion-hired',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,80})\s+trông\s+như\s+đã\s+thuê\s+được\s+cả\s+tiếng\s+nói\s+công\s+luận/giu,
    replacement: '$1 đứng giữa đám đông, vẻ mặt như thể mọi người đã đứng về phía mình',
    message: 'Cụm “thuê được cả tiếng nói công luận” nghe như bài phân tích; đổi thành phản ứng đám đông.',
    genericSuggestion: '[Nhân vật] đứng giữa đám đông, vẻ mặt như thể mọi người đã đứng về phía mình.',
  },
  {
    id: 'user-next-step-not-noisy-replace',
    category: 'slogan',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Bước\s+đi\s+tiếp\s+theo\s+sẽ\s+không\s+ồn\s+ào:\s*([^.!?\n]{2,160})/giu,
    replacement: 'Tôi không nói thêm. Trước mắt, tôi phải $1',
    message: 'Câu “Bước đi tiếp theo sẽ không ồn ào” giống slogan; đổi thành hành động trước mắt.',
    genericSuggestion: 'Tôi không nói thêm. Trước mắt, tôi phải [hành động cụ thể].',
  },
  {
    id: 'user-voice-wants-investigation',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Giọng\s+([^,.!?\n]{2,40})\s+muốn\s+lôi\s+kéo\s+một\s+cuộc\s+([^.!?\n]{2,80})/giu,
    replacement: '$1 nói lớn, rõ ràng muốn mọi người ép bên liên quan kiểm tra ngay tại chỗ',
    message: 'Câu “giọng muốn lôi kéo...” là diễn giải AI; đổi thành hành động nói lớn và tác động cụ thể.',
    genericSuggestion: '[Nhân vật] nói lớn, rõ ràng muốn mọi người ép [bên liên quan] kiểm tra ngay tại chỗ.',
  },
  // Rule mới từ 3 truyện test: file âm thanh / phiếu gửi đồ / video 7 giây
  {
    id: 'user-object-as-living-thing',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Tôi\s+giữ\s+([^.!?\n]{2,70})\s+như\s+một\s+thứ\s+còn\s+sống/giu,
    replacement: 'Tôi giữ chặt $1, không để ai chạm vào',
    message: 'Ẩn dụ “giữ như một thứ còn sống” làm vật chứng bị văn chương hóa; đổi thành hành động giữ cụ thể.',
    genericSuggestion: 'Tôi giữ chặt [vật chứng], không để ai chạm vào.',
  },
  {
    id: 'user-thin-cold-smile',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /nụ\s+cười\s+(?:của\s+[^,.!?\n]{1,30}\s+)?(?:mỏng|mảnh)\s+và\s+lạnh/giu,
    replacement: 'nụ cười lạnh nhạt',
    message: 'Cụm “nụ cười mỏng/mảnh và lạnh” sáo, đổi thành mô tả gọn hơn.',
  },
  {
    id: 'user-pressure-not-abstract',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Áp\s+lực\s+không\s+phải\s+là\s+điều\s+trừu\s+tượng\s*[—-]\s*nó\s+nằm\s+([^.!?\n]{2,140})/giu,
    replacement: 'Áp lực nằm ngay $1',
    message: 'Câu “áp lực không phải là điều trừu tượng” là telling AI; bỏ phần giải thích và giữ chi tiết cụ thể.',
    genericSuggestion: 'Viết trực tiếp áp lực nằm ở đâu: màn hình, số người xem, ánh mắt, giấy tờ, tin nhắn.',
  },
  {
    id: 'user-voice-as-bargain',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Giọng\s+([^.!?\n]{0,40})\s+như\s+đặt\s+một\s+giao\s+kèo/giu,
    replacement: '$1 nói như đang ép tôi phải chọn ngay',
    message: 'Ẩn dụ “giọng như đặt một giao kèo” hơi AI; đổi thành ý ép lựa chọn cụ thể.',
  },
  {
    id: 'user-heart-running-wild',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Tim\s+tôi\s+như\s+lồng\s+lộn/giu,
    replacement: 'Tim tôi đập mạnh',
    message: 'Cụm “tim như lồng lộn” hơi quá đà; đổi thành phản ứng cơ thể tự nhiên hơn.',
  },
  {
    id: 'user-question-stone-air',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /Câu\s+hỏi\s+như\s+đặt\s+cục\s+đá\s+xuống\s+giữa\s+không\s+khí\.?,?/giu,
    replacement: 'Câu hỏi đó khiến vài người im lại.',
    message: 'Ẩn dụ “cục đá giữa không khí” gượng; đổi thành phản ứng của người xung quanh.',
  },
  {
    id: 'user-side-person-enters-game',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Người\s+tưởng\s+ở\s+(?:ngoài\s+)?lề\s+đã\s+bước\s+vào\s+giữa\s+ván\s+bài/giu,
    replacement: 'Người tưởng không liên quan lúc này lại xuất hiện đúng chỗ',
    message: 'Cụm “bước vào giữa ván bài” sân khấu hóa; đổi thành tình huống cụ thể.',
  },
  {
    id: 'user-small-truth-opens',
    category: 'slogan',
    severity: 'medium',
    mode: 'replace',
    pattern: /Một\s+mảnh\s+nhỏ\s+của\s+sự\s+thật\s+hé\s+ra\.?,?/giu,
    replacement: 'Tôi bắt đầu hiểu có người khác đứng sau chuyện này.',
    message: 'Câu “một mảnh nhỏ của sự thật hé ra” giống tổng kết AI; đổi thành nhận định cụ thể.',
  },
  {
    id: 'user-words-open-light-gap',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Lời\s+([^.!?\n]{0,35})\s+như\s+mở\s+một\s+khe\s+sáng/giu,
    replacement: 'Lời $1 khiến tôi chú ý',
    message: 'Ẩn dụ “mở một khe sáng” hơi AI; đổi thành phản ứng chú ý cụ thể.',
  },
  {
    id: 'user-pull-evidence-to-light',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /(?:đủ\s+để\s+)?kéo\s+([^.!?\n]{2,80})\s+vào\s+ánh\s+sáng/giu,
    replacement: 'giúp tôi kiểm tra $1 trước mặt mọi người',
    message: 'Cụm “kéo ... vào ánh sáng” sáo; đổi thành hành động kiểm tra cụ thể.',
    genericSuggestion: 'giúp tôi kiểm tra [vật chứng/chi tiết] trước mặt mọi người.',
  },
  {
    id: 'user-not-win-but-gap',
    category: 'slogan',
    severity: 'medium',
    mode: 'replace',
    pattern: /Lần\s+này\s+chúng\s+tôi\s+chưa\s+thắng,\s*nhưng\s+đã\s+tìm\s+được\s+khe\s+hở\s+để\s+bám\s+vào\.?,?/giu,
    replacement: 'Tôi chưa thắng. Nhưng ít nhất, họ không thể bắt tôi nhận lỗi ngay lúc này.',
    message: 'Câu “chưa thắng nhưng có khe hở” là slogan AI; đổi thành lợi thế cụ thể trong cảnh.',
  },
  {
    id: 'user-background-sound-chaos',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,120})\s+thành\s+một\s+thứ\s+nền\s+âm\s+hỗn\s+độn/giu,
    replacement: '$1 trộn vào nhau',
    message: 'Cụm “nền âm hỗn độn” hơi làm văn; đổi thành mô tả trực tiếp.',
  },
  {
    id: 'user-voice-string-heart',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /Giọng\s+con\s+nhỏ,\s*run,\s*kéo\s+một\s+sợi\s+gì\s+đó\s+vào\s+tim\s+tôi\.?,?/giu,
    replacement: 'Giọng con nhỏ và run. Tôi nghe mà nghẹn lại.',
    message: 'Ẩn dụ “kéo một sợi gì đó vào tim” gượng; đổi thành phản ứng cảm xúc trực tiếp.',
  },
  {
    id: 'user-file-becomes-trap',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,60})\s+không\s+còn\s+là\s+file,\s*nó\s+thành\s+tấm\s+bẫy/giu,
    replacement: '$1 không còn là một đoạn file bình thường nữa. Nó đã bị dùng để gài bẫy tôi',
    message: 'Cụm “file thành tấm bẫy” hơi poster; đổi thành câu rõ nghĩa hơn.',
  },
  {
    id: 'user-eyes-this-is-their-yard',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Ánh\s+mắt\s+anh\s+nói\s+rõ:\s*đây\s+là\s+sân\s+của\s+họ/giu,
    replacement: 'Cách anh ta nhìn quanh khiến tôi hiểu nơi này đã được họ chuẩn bị từ trước',
    message: 'Câu “ánh mắt nói rõ: đây là sân của họ” sân khấu hóa; đổi thành nhận biết cụ thể.',
  },
  {
    id: 'user-switch-flipped',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Câu\s+đó\s+như\s+bật\s+công\s+tắc\.?,?/giu,
    replacement: 'Sau câu đó, đám phóng viên bắt đầu ồn lên.',
    message: 'Ẩn dụ “bật công tắc” dễ AI; đổi thành phản ứng cụ thể.',
  },
  {
    id: 'user-black-streak-light',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,80})\s+theo\s+tôi\s+như\s+một\s+vệt\s+đen\s+giữa\s+ánh\s+sáng/giu,
    replacement: '$1 vẫn ám trong đầu tôi',
    message: 'Ẩn dụ “vệt đen giữa ánh sáng” văn hoa; đổi thành cảm giác nhớ/ám ảnh rõ hơn.',
  },
  {
    id: 'user-more-than-voice',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /người\s+ta\s+sẽ\s+lấy\s+đi\s+nhiều\s+hơn\s+tiếng\s+nói\s+của\s+mình/giu,
    replacement: 'họ sẽ kéo thêm người vô tội vào chuyện này',
    message: 'Câu “lấy đi nhiều hơn tiếng nói” trừu tượng; đổi thành hậu quả cụ thể.',
  },
  {
    id: 'user-countdown-hours-starts',
    category: 'slogan',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /(\d+|mười\s+hai|mười\s+lăm|hai\s+mươi\s+bốn)\s+tiếng\s+bắt\s+đầu\s+đếm\s+ngược/giu,
    replacement: 'Tôi chỉ còn $1 tiếng để xác minh',
    message: 'Câu “bắt đầu đếm ngược” giống slogan; đổi thành thời hạn cụ thể của nhân vật.',
  },
  {
    id: 'user-this-is-only-beginning',
    category: 'slogan',
    severity: 'medium',
    mode: 'replace',
    pattern: /Đây\s+mới\s+chỉ\s+là\s+bước\s+đầu\.?,?/giu,
    replacement: 'Tôi biết chuyện này chưa dừng ở đây.',
    message: 'Câu “đây mới chỉ là bước đầu” là slogan quen thuộc; đổi thành nhận định đời hơn.',
  },
  {
    id: 'user-decision-changed-attitude',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'replace',
    pattern: /Quyết\s+định\s+đó\s+thay\s+đổi\s+thái\s+độ\s+quanh\s+tôi\.?,?/giu,
    replacement: 'Sau câu đó, vài người nhìn tôi khác hẳn.',
    message: 'Câu “quyết định thay đổi thái độ” là telling; đổi thành phản ứng người xung quanh.',
  },
  {
    id: 'user-power-still-hanging',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Quyền\s+lực\s+của\s+([^.!?\n]{1,40})\s+vẫn\s+treo\s+đó/giu,
    replacement: '$1 vẫn còn cách gây sức ép',
    message: 'Cụm “quyền lực vẫn treo đó” trừu tượng; đổi thành sức ép cụ thể.',
  },
  {
    id: 'user-clue-out-of-dark',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,80})\s+như\s+dấu\s+vết\s+vừa\s+ló\s+ra\s+khỏi\s+tối/giu,
    replacement: '$1 là chi tiết tôi cần kiểm tra tiếp',
    message: 'Ẩn dụ “ló ra khỏi tối” văn hoa; đổi thành hành động kiểm tra tiếp.',
  },
  {
    id: 'user-card-as-promise',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /đặt\s+lên\s+lòng\s+bàn\s+tay\s+như\s+một\s+lời\s+hứa/giu,
    replacement: 'giữ chặt trong lòng bàn tay',
    message: 'Cụm “đặt lên lòng bàn tay như lời hứa” văn hoa; đổi thành hành động giữ cụ thể.',
  },

]

export const userVietnameseProseWarningRules: VietnameseProseRule[] = [
  {
    id: 'user-warning-too-many-toi-openings',
    category: 'unclear_sentence',
    severity: 'low',
    mode: 'warning',
    pattern: /(?:^|\n)(?:Tôi\s+[^.!?\n]+[.!?]\s*){3,}/g,
    message: 'Nhiều câu liên tiếp bắt đầu bằng “Tôi”, dễ làm nhịp văn đều và máy.',
    genericSuggestion: 'Đổi một vài câu sang mở đầu bằng hành động, bối cảnh, hoặc phản ứng của người khác.',
  },
  {
    id: 'user-warning-administrative-dialogue',
    category: 'dialogue_role',
    severity: 'low',
    mode: 'warning',
    pattern: /triệu tập họp phụ huynh khẩn|ở lại để làm rõ|xử lý nghiêm/gi,
    message: 'Một số câu thoại hơi hành chính/sạch quá, nên làm đời hơn theo vai nói.',
    genericSuggestion: 'Thêm vai xưng hô cụ thể: “Mọi người bình tĩnh”, “phiền cô ở lại để đối chiếu...”, “nhà trường sẽ kiểm tra ngay”.',
  },
  {
    id: 'user-warning-evidence-as-heavy-object',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'warning',
    pattern: /như\s+một\s+(?:viên\s+đá|hòn\s+đá|khối\s+đá)/gi,
    message: 'So sánh vật chứng/cảm xúc với đá thường làm câu nặng và AI.',
    genericSuggestion: 'Đổi thành hành động cụ thể: giữ chặt, cất vào túi, đặt lên bàn, không để ai chạm vào.',
  },
  {
    id: 'user-warning-showbiz-poster-metaphors',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'warning',
    pattern: /ván\s+bài|vệt\s+đen\s+giữa\s+ánh\s+sáng|tấm\s+bẫy|bật\s+công\s+tắc|cục\s+đá\s+xuống\s+giữa\s+không\s+khí/giu,
    message: 'Cụm ẩn dụ kiểu poster/sân khấu hóa còn mùi AI.',
    genericSuggestion: 'Đổi thành hành động hoặc phản ứng cụ thể: ai im lại, ai nhìn sang, ai cầm giấy, ai bước vào.',
  },
  {
    id: 'user-warning-truth-light-metaphor',
    category: 'slogan',
    severity: 'medium',
    mode: 'warning',
    pattern: /sự\s+thật\s+hé\s+ra|kéo\s+[^.!?\n]{2,80}\s+vào\s+ánh\s+sáng|khe\s+hở\s+để\s+bám\s+vào/giu,
    message: 'Cụm “sự thật hé ra/kéo vào ánh sáng/khe hở” là câu tổng kết AI.',
    genericSuggestion: 'Viết cụ thể nhân vật phát hiện gì, giữ vật chứng gì, sẽ hỏi ai hoặc kiểm tra ở đâu.',
  },
  {
    id: 'user-warning-countdown-ending',
    category: 'slogan',
    severity: 'medium',
    mode: 'warning',
    pattern: /bắt\s+đầu\s+đếm\s+ngược|đây\s+mới\s+chỉ\s+là\s+bước\s+đầu|chuyện\s+này\s+chưa\s+dừng\s+ở\s+đây/giu,
    message: 'Câu kết kiểu countdown/bước đầu dễ thành slogan.',
    genericSuggestion: 'Kết bằng dữ kiện cụ thể: tin nhắn, người xuất hiện, vật chứng mới, thời hạn rõ, hoặc hành động tiếp theo.',
  },

]
