import type { VietnameseProseRule } from './vietnameseProseQuality.js'

function normalizeEvidencePlace(input: string) {
  const value = String(input || '').trim().toLowerCase()
  if (!value) return 'túi áo'
  if (value.includes('lòng áo') || value.includes('ngực') || value.includes('trước ngực')) return 'túi áo'
  if (value.includes('tay áo')) return 'tay áo'
  if (value === 'tay' || value.includes('trong tay')) return 'lòng bàn tay'
  return input.trim()
}

export const userVietnameseProseReplacementRules: VietnameseProseRule[] = [
  {
    id: 'user-remove-meta-recap-line',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'template-replace',
    pattern: /^(?:\s*(?:Hai câu tóm tắt nhanh|Tóm tắt nhanh|Ở chương trước|Nhắc lại một chút)\s*[:：][^\n]*(?:\n|$))+/giu,
    replacement: '',
    message: 'Dòng mở chương dạng meta/recap không thuộc nội dung truyện; xóa khỏi bản đọc.',
    genericSuggestion: 'Mở thẳng bằng cảnh truyện, hành động, lời thoại, hoặc hậu quả hiện tại.',
    examples: [
      {
        bad: 'Hai câu tóm tắt nhanh: nữ chính vừa bị đình chỉ. Bây giờ cô tới phòng họp.',
        good: 'Cửa phòng họp mở ra, và tờ quyết định đình chỉ đã nằm sẵn trên bàn.',
      },
    ],
  },
  {
    id: 'user-object-small-stone-template',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /(Tôi\s+(?:giữ|cầm|nắm))\s+([^.!?\n]{2,60})\s+như\s+một\s+viên\s+đá\s+nhỏ\s+trong\s+([^.!?\n]{2,50})/giu,
    replacement: (_match, captures) => {
      const object = captures[1]?.trim() || 'vật chứng đó'
      const place = normalizeEvidencePlace(captures[2] || '')
      return `Tôi giữ chặt ${object} trong ${place}, không để ai chạm vào`
    },
    message: 'Ẩn dụ vật chứng như “viên đá nhỏ” gượng; đổi thành hành động giữ vật chứng cụ thể.',
    genericSuggestion: 'Tôi giữ chặt [vật chứng] trong [túi áo/lòng bàn tay/túi xách], không để ai chạm vào.',
    examples: [
      {
        bad: 'Tôi giữ mẩu giấy như một viên đá nhỏ trong lòng áo.',
        good: 'Tôi giữ chặt mẩu giấy trong túi áo, không để ai chạm vào.',
      },
    ],
  },
  {
    id: 'user-speech-like-needle',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Lời\s+(?:nói|đó|ấy)\s+như\s+kim\s+châm\s+vào\s+([^.!?\n]{2,80})/giu,
    replacement: (_match, captures) => {
      const target = captures[0]?.trim() || 'tôi'
      return `Câu đó khiến vài người quay sang nhìn ${target}`
    },
    message: 'Ẩn dụ “lời nói như kim châm” sáo; đổi thành phản ứng cụ thể của người xung quanh.',
    genericSuggestion: 'Câu đó khiến [người xung quanh] quay sang nhìn [nhân vật] với thái độ cụ thể.',
    examples: [
      {
        bad: 'Lời nói như kim châm vào mặt tôi giữa đám đông.',
        good: 'Câu đó khiến vài phụ huynh quay sang nhìn tôi khó chịu.',
      },
    ],
  },
  {
    id: 'user-eyes-stuck-short-form',
    category: 'collocation',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Mắt\s+tôi\s+vẫn\s+dán\s+vào\s+([^.!?\n]{2,80})/giu,
    replacement: 'Tôi vẫn nhìn chằm chằm vào $1',
    message: 'Cụm “mắt tôi vẫn dán vào...” còn giọng AI/convert; đổi thành hành động nhìn cụ thể.',
    genericSuggestion: 'Tôi vẫn nhìn chằm chằm vào [vật/điểm cần chú ý].',
  },
  {
    id: 'user-crowded-like-beehive',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,60})\s+chật\s+như\s+tổ\s+ong\s+([^.!?\n]{0,50})/giu,
    replacement: (_match, captures) => {
      const place = captures[0]?.trim() || 'Nơi đó'
      const tail = captures[1]?.trim()
      return `${place} ${tail ? `${tail} ` : ''}chật kín người`.replace(/\s+/g, ' ').trim()
    },
    message: 'So sánh “chật như tổ ong” hơi AI; đổi thành mô tả trực tiếp.',
    genericSuggestion: '[Địa điểm] chật kín [người/khách/phụ huynh].',
    examples: [
      {
        bad: 'Cổng trường quốc tế chật như tổ ong buổi tan học.',
        good: 'Cổng trường quốc tế giờ tan học chật kín phụ huynh.',
      },
    ],
  },
  {
    id: 'user-warm-smell-collocation',
    category: 'collocation',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /tay\s+còn\s+ấm\s+mùi\s+([^,.!?\n]{2,40})/giu,
    replacement: 'trên người vẫn còn thoang thoảng mùi $1',
    message: 'Cụm “tay còn ấm mùi...” sai collocation; đổi thành mùi còn vương trên người/áo.',
    genericSuggestion: 'Trên áo/người [nhân vật] vẫn còn thoang thoảng mùi [mùi cụ thể].',
  },
  {
    id: 'user-public-opinion-hired',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,80})\s+trông\s+như\s+đã\s+thuê\s+được\s+cả\s+tiếng\s+nói\s+công\s+luận/giu,
    replacement: '$1 đứng giữa đám đông, vẻ mặt như thể mọi người đã đứng về phía mình',
    message: 'Cụm “thuê được cả tiếng nói công luận” nghe như bài phân tích; đổi thành phản ứng đám đông.',
    genericSuggestion: '[Nhân vật] đứng giữa đám đông, vẻ mặt như thể mọi người đã đứng về phía mình.',
  },
  {
    id: 'user-next-step-not-noisy-replace',
    category: 'slogan',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Bước\s+đi\s+tiếp\s+theo\s+sẽ\s+không\s+ồn\s+ào:\s*([^.!?\n]{2,160})/giu,
    replacement: 'Tôi không nói thêm. Trước mắt, tôi phải $1',
    message: 'Câu “Bước đi tiếp theo sẽ không ồn ào” giống slogan; đổi thành hành động trước mắt.',
    genericSuggestion: 'Tôi không nói thêm. Trước mắt, tôi phải [hành động cụ thể].',
  },
  {
    id: 'user-voice-wants-investigation',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Giọng\s+([^,.!?\n]{2,40})\s+muốn\s+lôi\s+kéo\s+một\s+cuộc\s+([^.!?\n]{2,80})/giu,
    replacement: '$1 nói lớn, rõ ràng muốn mọi người ép bên liên quan kiểm tra ngay tại chỗ',
    message: 'Câu “giọng muốn lôi kéo...” là diễn giải AI; đổi thành hành động nói lớn và tác động cụ thể.',
    genericSuggestion: '[Nhân vật] nói lớn, rõ ràng muốn mọi người ép [bên liên quan] kiểm tra ngay tại chỗ.',
  },
  // Rule mới từ 3 truyện test: file âm thanh / phiếu gửi đồ / video 7 giây
  {
    id: 'user-object-as-living-thing',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Tôi\s+giữ\s+([^.!?\n]{2,70})\s+như\s+một\s+thứ\s+còn\s+sống/giu,
    replacement: 'Tôi giữ chặt $1, không để ai chạm vào',
    message: 'Ẩn dụ “giữ như một thứ còn sống” làm vật chứng bị văn chương hóa; đổi thành hành động giữ cụ thể.',
    genericSuggestion: 'Tôi giữ chặt [vật chứng], không để ai chạm vào.',
  },
  {
    id: 'user-thin-cold-smile',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /nụ\s+cười\s+(?:của\s+[^,.!?\n]{1,30}\s+)?(?:mỏng|mảnh)\s+và\s+lạnh/giu,
    replacement: 'nụ cười lạnh nhạt',
    message: 'Cụm “nụ cười mỏng/mảnh và lạnh” sáo, đổi thành mô tả gọn hơn.',
  },
  {
    id: 'user-pressure-not-abstract',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Áp\s+lực\s+không\s+phải\s+là\s+điều\s+trừu\s+tượng\s*[—-]\s*nó\s+nằm\s+([^.!?\n]{2,140})/giu,
    replacement: 'Áp lực nằm ngay $1',
    message: 'Câu “áp lực không phải là điều trừu tượng” là telling AI; bỏ phần giải thích và giữ chi tiết cụ thể.',
    genericSuggestion: 'Viết trực tiếp áp lực nằm ở đâu: màn hình, số người xem, ánh mắt, giấy tờ, tin nhắn.',
  },
  {
    id: 'user-voice-as-bargain',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Giọng\s+([^.!?\n]{0,40})\s+như\s+đặt\s+một\s+giao\s+kèo/giu,
    replacement: '$1 nói như đang ép tôi phải chọn ngay',
    message: 'Ẩn dụ “giọng như đặt một giao kèo” hơi AI; đổi thành ý ép lựa chọn cụ thể.',
  },
  {
    id: 'user-heart-running-wild',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Tim\s+tôi\s+như\s+lồng\s+lộn/giu,
    replacement: 'Tim tôi đập mạnh',
    message: 'Cụm “tim như lồng lộn” hơi quá đà; đổi thành phản ứng cơ thể tự nhiên hơn.',
  },
  {
    id: 'user-question-stone-air',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /Câu\s+hỏi\s+như\s+đặt\s+cục\s+đá\s+xuống\s+giữa\s+không\s+khí\.?,?/giu,
    replacement: 'Câu hỏi đó khiến vài người im lại.',
    message: 'Ẩn dụ “cục đá giữa không khí” gượng; đổi thành phản ứng của người xung quanh.',
  },
  {
    id: 'user-side-person-enters-game',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Người\s+tưởng\s+ở\s+(?:ngoài\s+)?lề\s+đã\s+bước\s+vào\s+giữa\s+ván\s+bài/giu,
    replacement: 'Người tưởng không liên quan lúc này lại xuất hiện đúng chỗ',
    message: 'Cụm “bước vào giữa ván bài” sân khấu hóa; đổi thành tình huống cụ thể.',
  },
  {
    id: 'user-small-truth-opens',
    category: 'slogan',
    severity: 'medium',
    mode: 'replace',
    pattern: /Một\s+mảnh\s+nhỏ\s+của\s+sự\s+thật\s+hé\s+ra\.?,?/giu,
    replacement: 'Tôi bắt đầu hiểu có người khác đứng sau chuyện này.',
    message: 'Câu “một mảnh nhỏ của sự thật hé ra” giống tổng kết AI; đổi thành nhận định cụ thể.',
  },
  {
    id: 'user-words-open-light-gap',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Lời\s+([^.!?\n]{0,35})\s+như\s+mở\s+một\s+khe\s+sáng/giu,
    replacement: 'Lời $1 khiến tôi chú ý',
    message: 'Ẩn dụ “mở một khe sáng” hơi AI; đổi thành phản ứng chú ý cụ thể.',
  },
  {
    id: 'user-pull-evidence-to-light',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /(?:đủ\s+để\s+)?kéo\s+([^.!?\n]{2,80})\s+vào\s+ánh\s+sáng/giu,
    replacement: 'giúp tôi kiểm tra $1 trước mặt mọi người',
    message: 'Cụm “kéo ... vào ánh sáng” sáo; đổi thành hành động kiểm tra cụ thể.',
    genericSuggestion: 'giúp tôi kiểm tra [vật chứng/chi tiết] trước mặt mọi người.',
  },
  {
    id: 'user-not-win-but-gap',
    category: 'slogan',
    severity: 'medium',
    mode: 'replace',
    pattern: /Lần\s+này\s+chúng\s+tôi\s+chưa\s+thắng,\s*nhưng\s+đã\s+tìm\s+được\s+khe\s+hở\s+để\s+bám\s+vào\.?,?/giu,
    replacement: 'Tôi chưa thắng. Nhưng ít nhất, họ không thể bắt tôi nhận lỗi ngay lúc này.',
    message: 'Câu “chưa thắng nhưng có khe hở” là slogan AI; đổi thành lợi thế cụ thể trong cảnh.',
  },
  {
    id: 'user-background-sound-chaos',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,120})\s+thành\s+một\s+thứ\s+nền\s+âm\s+hỗn\s+độn/giu,
    replacement: '$1 trộn vào nhau',
    message: 'Cụm “nền âm hỗn độn” hơi làm văn; đổi thành mô tả trực tiếp.',
  },
  {
    id: 'user-voice-string-heart',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /Giọng\s+con\s+nhỏ,\s*run,\s*kéo\s+một\s+sợi\s+gì\s+đó\s+vào\s+tim\s+tôi\.?,?/giu,
    replacement: 'Giọng con nhỏ và run. Tôi nghe mà nghẹn lại.',
    message: 'Ẩn dụ “kéo một sợi gì đó vào tim” gượng; đổi thành phản ứng cảm xúc trực tiếp.',
  },
  {
    id: 'user-file-becomes-trap',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,60})\s+không\s+còn\s+là\s+file,\s*nó\s+thành\s+tấm\s+bẫy/giu,
    replacement: '$1 không còn là một đoạn file bình thường nữa. Nó đã bị dùng để gài bẫy tôi',
    message: 'Cụm “file thành tấm bẫy” hơi poster; đổi thành câu rõ nghĩa hơn.',
  },
  {
    id: 'user-eyes-this-is-their-yard',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Ánh\s+mắt\s+anh\s+nói\s+rõ:\s*đây\s+là\s+sân\s+của\s+họ/giu,
    replacement: 'Cách anh ta nhìn quanh khiến tôi hiểu nơi này đã được họ chuẩn bị từ trước',
    message: 'Câu “ánh mắt nói rõ: đây là sân của họ” sân khấu hóa; đổi thành nhận biết cụ thể.',
  },
  {
    id: 'user-switch-flipped',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Câu\s+đó\s+như\s+bật\s+công\s+tắc\.?,?/giu,
    replacement: 'Sau câu đó, đám phóng viên bắt đầu ồn lên.',
    message: 'Ẩn dụ “bật công tắc” dễ AI; đổi thành phản ứng cụ thể.',
  },
  {
    id: 'user-black-streak-light',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,80})\s+theo\s+tôi\s+như\s+một\s+vệt\s+đen\s+giữa\s+ánh\s+sáng/giu,
    replacement: '$1 vẫn ám trong đầu tôi',
    message: 'Ẩn dụ “vệt đen giữa ánh sáng” văn hoa; đổi thành cảm giác nhớ/ám ảnh rõ hơn.',
  },
  {
    id: 'user-more-than-voice',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /người\s+ta\s+sẽ\s+lấy\s+đi\s+nhiều\s+hơn\s+tiếng\s+nói\s+của\s+mình/giu,
    replacement: 'họ sẽ kéo thêm người vô tội vào chuyện này',
    message: 'Câu “lấy đi nhiều hơn tiếng nói” trừu tượng; đổi thành hậu quả cụ thể.',
  },
  {
    id: 'user-countdown-hours-starts',
    category: 'slogan',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /(\d+|mười\s+hai|mười\s+lăm|hai\s+mươi\s+bốn)\s+tiếng\s+bắt\s+đầu\s+đếm\s+ngược/giu,
    replacement: 'Tôi chỉ còn $1 tiếng để xác minh',
    message: 'Câu “bắt đầu đếm ngược” giống slogan; đổi thành thời hạn cụ thể của nhân vật.',
  },
  {
    id: 'user-this-is-only-beginning',
    category: 'slogan',
    severity: 'medium',
    mode: 'replace',
    pattern: /Đây\s+mới\s+chỉ\s+là\s+bước\s+đầu\.?,?/giu,
    replacement: 'Tôi biết chuyện này chưa dừng ở đây.',
    message: 'Câu “đây mới chỉ là bước đầu” là slogan quen thuộc; đổi thành nhận định đời hơn.',
  },
  {
    id: 'user-decision-changed-attitude',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'replace',
    pattern: /Quyết\s+định\s+đó\s+thay\s+đổi\s+thái\s+độ\s+quanh\s+tôi\.?,?/giu,
    replacement: 'Sau câu đó, vài người nhìn tôi khác hẳn.',
    message: 'Câu “quyết định thay đổi thái độ” là telling; đổi thành phản ứng người xung quanh.',
  },
  {
    id: 'user-power-still-hanging',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Quyền\s+lực\s+của\s+([^.!?\n]{1,40})\s+vẫn\s+treo\s+đó/giu,
    replacement: '$1 vẫn còn cách gây sức ép',
    message: 'Cụm “quyền lực vẫn treo đó” trừu tượng; đổi thành sức ép cụ thể.',
  },
  {
    id: 'user-clue-out-of-dark',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,80})\s+như\s+dấu\s+vết\s+vừa\s+ló\s+ra\s+khỏi\s+tối/giu,
    replacement: '$1 là chi tiết tôi cần kiểm tra tiếp',
    message: 'Ẩn dụ “ló ra khỏi tối” văn hoa; đổi thành hành động kiểm tra tiếp.',
  },
  {
    id: 'user-card-as-promise',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /đặt\s+lên\s+lòng\s+bàn\s+tay\s+như\s+một\s+lời\s+hứa/giu,
    replacement: 'giữ chặt trong lòng bàn tay',
    message: 'Cụm “đặt lên lòng bàn tay như lời hứa” văn hoa; đổi thành hành động giữ cụ thể.',
  },

  // Rule mới từ truyện test: Mảnh vải mẫu / Bản hợp đồng
  {
    id: 'user-flickering-fluorescent-light',
    category: 'collocation',
    severity: 'low',
    mode: 'replace',
    pattern: /đèn\s+huỳnh\s+quang\s+bật\s+bật/giu,
    replacement: 'đèn huỳnh quang hơi nhấp nháy',
    message: 'Cụm “đèn huỳnh quang bật bật” sai tai; đổi thành mô tả tự nhiên hơn.',
  },
  {
    id: 'user-fabric-idea-waits-stage',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'replace',
    pattern: /mỗi\s+tấm\s+là\s+một\s+ý\s+tưởng\s+chờ\s+ra\s+sân\s+khấu/giu,
    replacement: 'mỗi tấm là một mẫu chuẩn bị đưa vào buổi trình diễn',
    message: 'Câu “ý tưởng chờ ra sân khấu” hơi văn hoa; đổi thành chức năng cụ thể của mẫu vải.',
  },
  {
    id: 'user-look-like-prepared-file',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /([^.!?\n]{1,80})\s+nhìn\s+tôi\s+như\s+đọc\s+một\s+hồ\s+sơ\s+đã\s+soạn\s+sẵn/giu,
    replacement: '$1 nhìn tôi như đã chuẩn bị sẵn kết luận',
    message: 'Ẩn dụ “đọc một hồ sơ đã soạn sẵn” hơi AI; đổi thành thái độ đã kết luận sẵn.',
    genericSuggestion: '[Nhân vật] nhìn tôi như đã chuẩn bị sẵn kết luận.',
  },
  {
    id: 'user-words-sucked-into-throat',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /lời\s+([^.!?\n]{0,40})\s+như\s+bị\s+hút\s+vào\s+cổ\s+họng/giu,
    replacement: 'giọng $1 nhỏ đến mức gần như không nghe rõ',
    message: 'Cụm “lời như bị hút vào cổ họng” gượng; đổi thành âm lượng/giọng nói cụ thể.',
  },
  {
    id: 'user-contract-as-hammer',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /nhắc\s+tới\s+([^.!?\n]{2,50})\s+như\s+một\s+cây\s+búa/giu,
    replacement: 'nhắc tới $1 để ép mọi người im lại',
    message: 'Ẩn dụ “như một cây búa” gượng; đổi thành tác dụng gây sức ép trong cảnh.',
  },
  {
    id: 'user-public-pressure-changes-tone',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Áp\s+lực\s+công\s+chúng\s+bắt\s+đầu\s+chuyển\s+tông/giu,
    replacement: 'Vài người bắt đầu giơ điện thoại lên quay, tiếng xì xào cũng lớn hơn',
    message: 'Câu “áp lực công chúng chuyển tông” là telling; đổi thành hành động cụ thể của đám đông.',
  },
  {
    id: 'user-phrase-like-lid-closing',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Câu\s+["“]([^"”\n]{2,80})["”]\s+như\s+cái\s+nắp\s+đóng\s+xuống/giu,
    replacement: 'Sau câu “$1”, mọi người hiểu quyết định tạm thời đã được đưa ra',
    message: 'Ẩn dụ “cái nắp đóng xuống” văn hoa; đổi thành hệ quả cụ thể sau câu nói.',
  },
  {
    id: 'user-eye-saw-evidence',
    category: 'collocation',
    severity: 'medium',
    mode: 'replace',
    pattern: /con\s+mắt\s+đã\s+thấy/giu,
    replacement: 'tôi đã nhìn thấy',
    message: 'Cụm “con mắt đã thấy” sai tai; đổi thành chủ thể người kể trực tiếp.',
  },
  {
    id: 'user-ear-heart-buzzing',
    category: 'collocation',
    severity: 'medium',
    mode: 'replace',
    pattern: /Tim\s+tôi\s+lùng\s+bùng/giu,
    replacement: 'Tai tôi ù đi',
    message: 'Cụm “tim tôi lùng bùng” sai collocation; đổi thành phản ứng cơ thể tự nhiên hơn.',
  },
  {
    id: 'user-clip-valuable-thing-under-shirt',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /như\s+kẹp\s+một\s+mảnh\s+đồ\s+quý\s+dưới\s+áo/giu,
    replacement: 'giữ thật chặt trong lòng bàn tay',
    message: 'Cụm “mảnh đồ quý dưới áo” gượng; đổi thành hành động giữ vật chứng cụ thể.',
  },
  {
    id: 'user-voice-as-stamp',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /giọng\s+([^.!?\n]{0,30})\s+như\s+đóng\s+dấu/giu,
    replacement: 'giọng $1 dứt khoát',
    message: 'Ẩn dụ “giọng như đóng dấu” hơi convert/AI; đổi thành sắc thái giọng cụ thể.',
  },
  {
    id: 'user-close-rebuttal-path',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /đóng\s+chặt\s+một\s+lối\s+phản\s+bác/giu,
    replacement: 'chặn trước mọi lời phản bác',
    message: 'Cụm “đóng chặt một lối phản bác” gượng; đổi thành ý rõ hơn.',
  },
  {
    id: 'user-eyes-shifting',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Tôi\s+cảm\s+nhận\s+ánh\s+mắt\s+dịch\s+chuyển/giu,
    replacement: 'Tôi thấy mọi người bắt đầu quay sang nhìn nhau',
    message: 'Câu “cảm nhận ánh mắt dịch chuyển” trừu tượng; đổi thành phản ứng nhìn thấy được.',
  },
  {
    id: 'user-evidence-speaks-that',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,60})\s+nói\s+rằng\s+ai\s+đó\s+đã\s+([^.!?\n]{2,100})/giu,
    replacement: '$1 cho thấy có người đã $2',
    message: 'Không để vật chứng “nói rằng”; đổi thành “cho thấy” hoặc suy luận của nhân vật.',
    genericSuggestion: '[Vật chứng] cho thấy có người đã [hành động cụ thể].',
  },
  {
    id: 'user-evidence-asks-what-next',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /Dấu\s+mực\s+lệch\s+đã\s+xuất\s+hiện\.\s*Nó\s+hỏi\s+tôi\s+phải\s+làm\s+gì\s+tiếp\s+theo\.?/giu,
    replacement: 'Dấu mực lệch nằm ngay trước mắt. Tôi không thể ký khi chưa biết ai đã sửa trang này.',
    message: 'Vật chứng không “hỏi”; đổi thành quyết định cụ thể của nhân vật.',
  },
  {
    id: 'user-fire-awake-inside',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /trong\s+lòng\s+lửa\s+tỉnh/giu,
    replacement: 'tôi cố giữ tỉnh táo',
    message: 'Cụm “trong lòng lửa tỉnh” rất gượng/AI; đổi thành trạng thái cụ thể.',
  },
  {
    id: 'user-eyes-say-usb',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /ánh\s+mắt\s+cô\s+nói\s+["“]USB["”]/giu,
    replacement: 'cô liếc xuống túi áo tôi, ra hiệu về chiếc USB',
    message: 'Câu “ánh mắt cô nói USB” sai tự nhiên; đổi thành cử chỉ cụ thể.',
  },
  {
    id: 'user-power-not-only-seal',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /quyền\s+lực\s+không\s+chỉ\s+nằm\s+trên\s+con\s+dấu/giu,
    replacement: 'chỉ cần giữ được bản gốc và chứng cứ, họ chưa thể ép tôi ký ngay',
    message: 'Cụm “quyền lực nằm trên con dấu” trừu tượng; đổi thành lợi thế cụ thể.',
  },
  {
    id: 'user-door-like-appointment',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Cửa\s+([^.!?\n]{0,50})\s+đóng\s+lại\s+sau\s+lưng\s+như\s+một\s+lời\s+hẹn/giu,
    replacement: 'Cửa $1 khép lại sau lưng. Tôi biết chuyện chưa dừng ở đây',
    message: 'Ẩn dụ “cửa như một lời hẹn” văn hoa; đổi thành nhận định cụ thể.',
  },
  {
    id: 'user-mother-must-be-awake',
    category: 'collocation',
    severity: 'high',
    mode: 'replace',
    pattern: /Mẹ\s+phải\s+tỉnh/giu,
    replacement: 'Tôi phải tỉnh táo',
    message: 'Câu “Mẹ phải tỉnh” gượng; đổi thành lời tự nhắc tự nhiên hơn.',
  },
  {
    id: 'user-follow-clue-to-end',
    category: 'slogan',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Tôi\s+có\s+một\s+manh\s+mối,\s*và\s+sẽ\s+theo\s+nó\s+tới\s+cùng\.?/giu,
    replacement: 'Tôi giữ chặt vật chứng trong túi. Trước hết, tôi phải tìm ra người đã động tay vào nó.',
    message: 'Câu “theo manh mối tới cùng” là slogan; đổi thành hành động tiếp theo cụ thể.',
  },
  {
    id: 'user-go-find-truth-ending',
    category: 'slogan',
    severity: 'medium',
    mode: 'replace',
    pattern: /Tôi\s+đi\s+theo\s+hướng\s+khác:\s*đi\s+tìm\s+sự\s+thật\.?/giu,
    replacement: 'Tôi kiểm tra lại USB trong balo rồi gọi cho trợ lý lần nữa.',
    message: 'Câu “đi tìm sự thật” là slogan; đổi thành hành động cụ thể.',
  },


  // Market benchmark cleanup: giữ chất truyện mạng, chỉ dọn rác câu / metaphor AI / lỗi paste.

    // Batch 7: dọn câu tối nghĩa / metaphor AI từ truyện full 9 chương và các truyện test gần nhất.
    
    {
    id: 'user-batch7-not-everything-but-enough',
    category: 'slogan',
    severity: 'medium',
    mode: 'replace',
    pattern: /Không\s+phải\s+tất\s+cả,\s*nhưng\s+đủ\s+để\s+([^.!?\n]{2,120})/giu,
    replacement: 'Chừng đó đã đủ để $1',
    message: 'Câu “Không phải tất cả, nhưng đủ để...” là kiểu tổng kết AI; đổi thành câu hành động rõ hơn.',
  },
  {
    id: 'user-batch7-air-tightens',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /không\s+khí\s+(?:như\s+)?(?:bị\s+)?siết\s+lại/giu,
    replacement: 'cả phòng im hẳn',
    message: 'Cụm “không khí siết lại” hơi văn hoa; đổi thành phản ứng cụ thể của đám đông.',
  },
  {
    id: 'user-batch7-silence-has-weight',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /sự\s+im\s+lặng\s+(?:nặng|đè)\s+[^.!?\n]{0,80}/giu,
    replacement: 'cả phòng im đến mức nghe rõ tiếng thở',
    message: 'Ẩn dụ “sự im lặng nặng/đè” lặp kiểu AI; đổi thành âm thanh cụ thể.',
  },
  {
    id: 'user-batch7-eyes-like-knife',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /ánh\s+mắt\s+[^.!?\n]{0,40}\s+như\s+(?:dao|mũi\s+dao|lưỡi\s+dao)[^.!?\n]*/giu,
    replacement: 'ánh mắt đó lạnh hẳn đi',
    message: 'So sánh ánh mắt với dao bị lặp và sáo; đổi thành sắc thái nhìn cụ thể.',
  },
  {
    id: 'user-batch7-sentence-falls-right-place',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /từng\s+chữ\s+rơi\s+vào\s+đúng\s+chỗ\s+trống/giu,
    replacement: 'câu đó khiến vài người lập tức nhìn sang vật chứng trên bàn',
    message: 'Cụm “từng chữ rơi vào đúng chỗ trống” văn hoa; đổi thành phản ứng trong cảnh.',
  },
  {
    id: 'user-batch7-thread-as-clue',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,80})\s+như\s+một\s+sợi\s+chỉ\s+[^.!?\n]{0,80}/giu,
    replacement: '$1 là chi tiết tôi cần kiểm tra tiếp',
    message: 'Ẩn dụ “sợi chỉ” dễ AI; đổi thành chức năng điều tra cụ thể.',
  },
  {
    id: 'user-batch7-opened-a-gap',
    category: 'slogan',
    severity: 'medium',
    mode: 'replace',
    pattern: /(?:mở|tạo|xé)\s+(?:ra\s+)?một\s+khe\s+hở\s+(?:đầu\s+tiên|nhỏ|hiếm hoi)?/giu,
    replacement: 'khiến họ không thể kết luận ngay',
    message: 'Cụm “khe hở đầu tiên” bị dùng nhiều; đổi thành lợi thế cụ thể trong cảnh.',
  },
  {
    id: 'user-batch7-evidence-is-arrow',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,80})\s+như\s+(?:một\s+)?(?:mũi\s+tên|kim\s+chỉ\s+nam)\s+[^.!?\n]{0,80}/giu,
    replacement: '$1 cho tôi biết phải kiểm tra điểm nào tiếp theo',
    message: 'Ẩn dụ vật chứng như mũi tên/kim chỉ nam hơi AI; đổi thành tác dụng điều tra.',
  },
  {
    id: 'user-batch7-truth-surface',
    category: 'slogan',
    severity: 'medium',
    mode: 'replace',
    pattern: /sự\s+thật\s+(?:bắt\s+đầu\s+)?(?:trồi|ló|hiện)\s+(?:lên|ra)[^.!?\n]*/giu,
    replacement: 'tôi bắt đầu thấy có người đã chuẩn bị chuyện này từ trước',
    message: 'Câu “sự thật ló/trồi/hiện ra” là tổng kết AI; đổi thành nhận định cụ thể.',
  },
  {
    id: 'user-batch7-stage-word',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,80})\s+như\s+(?:một\s+)?(?:sân\s+khấu|màn\s+kịch)\s+[^.!?\n]{0,80}/giu,
    replacement: '$1 rõ ràng đã được sắp đặt từ trước',
    message: 'So sánh tình huống với sân khấu/màn kịch bị lặp; đổi thành ý sắp đặt cụ thể.',
  },
  {
    id: 'user-batch7-heart-cold-or-sinks',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /tim\s+tôi\s+(?:lạnh\s+lại|chìm\s+xuống|rơi\s+xuống)[^.!?\n]*/giu,
    replacement: 'tôi khựng lại một nhịp',
    message: 'Phản ứng “tim lạnh/chìm/rơi” hơi sáo; đổi thành phản ứng cơ thể gọn hơn.',
  },
  {
    id: 'user-batch7-price-not-abstract',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Cái\s+giá\s+(?:phải\s+trả\s+)?(?:không\s+)?(?:còn\s+)?(?:nằm\s+)?(?:ở|trong)\s+([^.!?\n]{2,120})/giu,
    replacement: 'Nếu chuyện này lan ra, $1 sẽ bị ảnh hưởng trước',
    message: 'Câu “cái giá nằm ở...” trừu tượng; đổi thành hậu quả cụ thể.',
  },
  {
    id: 'user-batch7-not-win-but-breath',
    category: 'slogan',
    severity: 'medium',
    mode: 'replace',
    pattern: /Tôi\s+chưa\s+thắng,\s*nhưng\s+(?:ít\s+nhất\s+)?(?:đã\s+)?(?:có|giành|lấy)\s+được\s+[^.!?\n]{2,120}/giu,
    replacement: 'Tôi chưa thắng. Nhưng lúc này, họ không thể ép tôi nhận lỗi ngay.',
    message: 'Câu “chưa thắng nhưng...” bị dùng như kết chương; đổi thành lợi thế cụ thể.',
  },
  {
    id: 'user-batch7-the-game-not-over',
    category: 'slogan',
    severity: 'medium',
    mode: 'replace',
    pattern: /(?:trò\s+chơi|ván\s+này|chuyện\s+này)\s+(?:còn\s+lâu\s+mới\s+)?(?:chưa\s+)?(?:kết\s+thúc|dừng\s+lại)[^.!?\n]*/giu,
    replacement: 'Tôi biết họ sẽ còn ra tay tiếp.',
    message: 'Câu “trò chơi/chuyện này chưa kết thúc” là slogan cuối chương; đổi thành dự cảm cụ thể.',
  },
  {
    id: 'user-batch7-light-dark-metaphor',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /(?:ánh\s+sáng|bóng\s+tối|vệt\s+đen|khe\s+sáng)\s+[^.!?\n]{0,80}(?:sự\s+thật|bí\s+mật|âm\s+mưu)[^.!?\n]*/giu,
    replacement: 'chi tiết đó khiến tôi phải kiểm tra lại toàn bộ hồ sơ',
    message: 'Ẩn dụ ánh sáng/bóng tối với sự thật bị AI hóa; đổi thành hành động kiểm tra.',
  },
  {
    id: 'user-batch7-voice-too-abstract',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'warn',
    pattern: /giọng\s+[^.!?\n]{0,40}\s+như\s+[^.!?\n]{2,80}/giu,
    message: 'Câu “giọng ... như ...” có thể hơi sáo hoặc lộ AI nếu lặp nhiều, nhưng không auto sửa vì dễ phá chủ thể câu.',
    genericSuggestion: 'Chỉ sửa thủ công khi câu thật sự gượng. Ví dụ có thể đổi thành “Anh ta hạ giọng”, “Giọng cô ấy thấp xuống”, hoặc giữ nguyên nếu hợp nhịp truyện mạng.',
  },
  {
    id: 'user-batch7-voice-too-abstract',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'warning',
    pattern: /Giọng\s+[^.!?\n]{0,40}\s+như\s+[^.!?\n]{2,80}/giu,
    message: 'Câu “giọng ... như ...” dễ sinh ẩn dụ gượng. Không auto sửa hàng loạt vì dễ phá chủ thể câu.',
    genericSuggestion: 'Đổi thủ công sang sắc thái nói cụ thể: “Anh ta hạ giọng”, “Giọng cô ấy thấp xuống”, “Người đó nói chậm lại”.',
  },
  {
    id: 'user-batch7-object-not-speaking',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,80})\s+(?:đang\s+)?(?:nói|hỏi|kể)\s+(?:với\s+)?tôi\s+rằng\s+([^.!?\n]{2,140})/giu,
    replacement: '$1 cho thấy $2',
    message: 'Không để vật chứng “nói/hỏi/kể với tôi”; đổi thành “cho thấy” để câu tự nhiên hơn.',
  },
  {
    id: 'user-batch7-abstract-power-pressure',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /(?:quyền\s+lực|áp\s+lực)\s+(?:lúc\s+này\s+)?(?:đang\s+)?(?:nằm|đè|treo)\s+(?:ở|trên|trong)\s+([^.!?\n]{2,100})/giu,
    replacement: 'Lúc này, $1 mới là thứ họ dùng để ép tôi',
    message: 'Câu quyền lực/áp lực nằm/đè/treo ở đâu đó hơi trừu tượng; đổi thành công cụ ép cụ thể.',
  },
  {
    id: 'market-cleanup-inline-genre-tags',
    category: 'output_cleanup',
    severity: 'high',
    mode: 'replace',
    pattern: /(?:^|\n)\s*(Lãng mạn|Trống|Nhạc và âm thanh|Chó|Toán học|Gia đình|Trái cây\s*&\s*rau)\s*(?=\n|$)/giu,
    replacement: '',
    message: 'Xóa tag/rác category bị dính vào nội dung chương.',
  },
  {
    id: 'market-cleanup-broken-blood-word',
    category: 'output_cleanup',
    severity: 'high',
    mode: 'replace',
    pattern: /M\/áu/giu,
    replacement: 'Máu',
    message: 'Sửa lỗi chữ bị chèn dấu slash.',
  },
  {
    id: 'market-cleanup-broken-doi-ending',
    category: 'output_cleanup',
    severity: 'medium',
    mode: 'replace',
    pattern: /trong\s+đờ\b/giu,
    replacement: 'trong đời',
    message: 'Sửa lỗi cụm “trong đờ” thành “trong đời”.',
  },
  {
    id: 'market-cleanup-stuck-ong-after-mai',
    category: 'output_cleanup',
    severity: 'medium',
    mode: 'replace',
    pattern: /mỉa\s+maiống/giu,
    replacement: 'mỉa mai',
    message: 'Sửa lỗi dính chữ rác sau “mỉa mai”.',
  },
  {
    id: 'market-room-silent-like-squeezed',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,40})\s+im\s+như\s+bị\s+bóp/giu,
    replacement: '$1 im phăng phắc',
    message: '“Im như bị bóp” là ẩn dụ gượng; đổi thành trạng thái im lặng tự nhiên hơn.',
  },
  {
    id: 'market-opening-mouth-cuts-air',
    category: 'collocation',
    severity: 'high',
    mode: 'template-replace',
    pattern: /tiếng\s+mở\s+miệng\s+của\s+([^.!?\n]{1,40})\s+cắt\s+không\s+khí/giu,
    replacement: 'giọng của $1 cắt ngang bầu không khí',
    message: '“Tiếng mở miệng” sai collocation; đổi thành “giọng... cắt ngang bầu không khí”.',
  },
  {
    id: 'market-cold-like-road-of-power',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'template-replace',
    pattern: /mắt\s+([^.!?\n]{1,40})\s+lạnh\s+như\s+đường\s+của\s+người\s+đã\s+có\s+quyền\s+quyết\s+định/giu,
    replacement: 'mắt $1 lạnh như đã nắm chắc quyền quyết định',
    message: '“Lạnh như đường của người...” tối nghĩa; đổi thành ý quyền lực rõ hơn.',
  },
  {
    id: 'market-file-like-holy-book',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'template-replace',
    pattern: /ôm\s+khư\s+khư\s+([^.!?\n]{1,50})\s+như\s+ôm\s+một\s+tờ\s+sổ\s+thánh/giu,
    replacement: 'ôm khư khư $1 như sợ ai giật mất',
    message: 'Ẩn dụ “sổ thánh” kỳ và lộ AI; đổi thành hành động cụ thể.',
  },
  {
    id: 'market-skull-fragile-breaks',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /Câu\s+nói\s+như\s+hộp\s+sọ\s+mỏng\s+manh\s+vỡ\s+ra/giu,
    replacement: 'Câu nói ấy khiến cả người nghe khựng lại',
    message: 'Ẩn dụ “hộp sọ mỏng manh vỡ ra” rất gượng và sai cảm giác; đổi thành phản ứng cụ thể.',
  },
  {
    id: 'market-sigh-pushes-through-crowd',
    category: 'collocation',
    severity: 'medium',
    mode: 'replace',
    pattern: /Một\s+tiếng\s+thở\s+dài\s+xô\s+qua\s+đám\s+người/giu,
    replacement: 'Một tiếng thở dài vang lên giữa đám người',
    message: '“Tiếng thở dài xô qua” sai tai; đổi thành cách diễn đạt tự nhiên hơn.',
  },
  {
    id: 'market-duplicate-sat-sat',
    category: 'collocation',
    severity: 'high',
    mode: 'template-replace',
    pattern: /kéo\s+sát\s+sát\s+([^.!?\n]{1,30})/giu,
    replacement: 'kéo sát $1',
    message: 'Sửa lỗi lặp “sát sát”.',
  },
  {
    id: 'market-shadows-changing-color',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /một\s+vài\s+chiếc\s+bóng\s+đang\s+đổi\s+sắc/giu,
    replacement: 'vài người im lặng đứng đó, vẻ mặt đã khác đi',
    message: '“Chiếc bóng đổi sắc” mơ hồ và lộ AI; đổi thành phản ứng người cụ thể.',
  },
  {
    id: 'market-eyes-like-judge',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Mọi\s+ánh\s+mắt\s+đổ\s+dồn\s+vào\s+([^.!?\n]{1,40})\s+như\s+một\s+phán\s+quan/giu,
    replacement: 'Mọi ánh mắt đổ dồn vào $1, chờ một câu xác nhận',
    message: '“Ánh mắt như phán quan” gượng; đổi thành áp lực chờ câu trả lời.',
  },
  {
    id: 'market-hands-cover-belly-like-child',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'template-replace',
    pattern: /Tay\s+([^.!?\n]{1,24})\s+che\s+lấy\s+bụng,\s*như\s+che\s+đứa\s+con\s+ai\s+đó/giu,
    replacement: 'Tay $1 vô thức đặt trước bụng, dáng vẻ hoảng hốt',
    message: '“Che bụng như che đứa con ai đó” tối nghĩa; đổi thành phản ứng cơ thể rõ hơn.',
  },
  {
    id: 'market-partner-representative-rushes-back',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /Một\s+cô\s+đại\s+diện\s+bên\s+đối\s+tác\s+[^.!?\n]{0,20}\s+bắt\s+đầu\s+vụt\s+lại/giu,
    replacement: 'Một cô đại diện phía đối tác lập tức quay lại',
    message: '“Bắt đầu vụt lại” tối nghĩa; đổi thành hành động rõ.',
  },
  {
    id: 'market-hall-contracts',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Tôi\s+cảm\s+được\s+cả\s+([^.!?\n]{1,30})\s+co\s+lại/giu,
    replacement: 'Tôi cảm thấy không khí quanh mình lập tức căng lên',
    message: '“Cả hội trường co lại” hơi AI; đổi thành không khí căng lên.',
  },
  {
    id: 'market-small-voice-like-needle',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Một\s+tiếng\s+gọi\s+nhỏ\s+xiu\s+như\s+kim\s+châm\s+vào\s+lòng/giu,
    replacement: 'Tiếng gọi nhỏ ấy khiến lòng tôi thắt lại',
    message: 'Ẩn dụ “kim châm vào lòng” hơi sáo; đổi thành phản ứng cảm xúc trực tiếp.',
  },
  {
    id: 'market-sentence-like-bottle-cap',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Câu\s+nói\s+như\s+mở\s+nút\s+chai/giu,
    replacement: 'Câu nói ấy lập tức kéo theo một loạt tiếng xì xào',
    message: '“Câu nói như mở nút chai” gượng; đổi thành hậu quả cụ thể.',
  },
  {
    id: 'market-eyes-like-contaminated-area',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /ánh\s+mắt\s+họ\s+xa\s+lạ\s+với\s+([^.!?\n]{1,40})\s+[—-]\s+như\s+một\s+vùng\s+nhiễm\s+bẩn/giu,
    replacement: 'ánh mắt họ nhìn $1 đã khác hẳn, lạnh nhạt và xa cách',
    message: '“Như một vùng nhiễm bẩn” quá nặng và lộ AI; đổi thành thái độ cụ thể.',
  },
  {
    id: 'market-cloud-into-light',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /kéo\s+đám\s+mây\s+[^.!?\n]{0,30}\s+ra\s+ánh\s+sáng/giu,
    replacement: 'kéo sự thật ra trước mặt mọi người',
    message: '“Kéo đám mây ra ánh sáng” là metaphor gượng; đổi thành mục tiêu rõ.',
  },
  {
    id: 'market-evidence-open-small-door',
    category: 'slogan',
    severity: 'medium',
    mode: 'warning',
    pattern: /mở\s+ra\s+một\s+cánh\s+cửa\s+nhỏ/giu,
    message: 'Cụm “mở ra một cánh cửa nhỏ” hơi AI nếu dùng nhiều; có thể giữ nếu nhịp chương cần cliffhanger.',
    genericSuggestion: 'Có thể đổi thành “cho tôi một hướng để lần tiếp” hoặc kết bằng hành động cụ thể.',
  },
  {
    id: 'market-concrete-loss-explaining',
    category: 'slogan',
    severity: 'medium',
    mode: 'warning',
    pattern: /đây\s+là\s+mất\s+mát\s+cụ\s+thể,\s*tiền\s+bạc\s+lẫn\s+uy\s+tín/giu,
    message: 'Câu giải thích hậu quả hơi lộ AI; nên để tình huống tự cho thấy thiệt hại.',
    genericSuggestion: 'Có thể thay bằng hành động: đối tác rời đi, nhân viên cúi đầu, hợp đồng bị gấp lại.',
  },
  {
    id: 'market-not-win-big-summary',
    category: 'slogan',
    severity: 'medium',
    mode: 'warning',
    pattern: /Tôi\s+không\s+thắng\s+to|Tôi\s+biết\s+mình\s+thua\s+một\s+ván|họ\s+thắng\s+ở\s+mặt\s+truyền\s+thông/giu,
    message: 'Câu tổng kết “thắng/thua một ván” dễ lặp và lộ AI nếu xuất hiện nhiều.',
    genericSuggestion: 'Kết bằng hành động/vật chứng cụ thể thay vì tự tổng kết.',
  },


  {
    id: 'batch-baby-baby-name-dup',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'template-replace',
    pattern: /\b(?:Đứa\s+bé\s+bé|đứa\s+bé\s+bé)\s+([A-ZÀ-Ỵ][\p{L}]{1,20})/giu,
    replacement: 'bé $1',
    message: 'Sửa lỗi lặp sau auto-fix kiểu “Đứa bé bé X”.',
    genericSuggestion: 'Viết gọn thành “bé X” hoặc “đứa trẻ”.',
  },
  {
    id: 'batch-paper-smell-wrong-word',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'replace',
    pattern: /mùi\s+giấy\s+bế,\s*keo\s+và\s+cà\s+phê/giu,
    replacement: 'mùi giấy mới, keo và cà phê',
    message: '“Giấy bế” khó hiểu trong ngữ cảnh prose; đổi thành “giấy mới”.',
  },
  {
    id: 'batch-rustling-like-falling-leaves',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Mọi\s+thứ\s+xào\s+xạc\s+như\s+lá\s+rụng/giu,
    replacement: 'Giấy tờ xào xạc trên mặt bàn',
    message: 'Ẩn dụ “xào xạc như lá rụng” không giúp drama; đổi thành hành động cụ thể.',
  },
  {
    id: 'batch-small-heart-squeezed',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /Trái\s+tim\s+bé\s+như\s+bị\s+ai\s+bóp\s+nhẹ/giu,
    replacement: 'Tim tôi như bị bóp nghẹt',
    message: '“Trái tim bé” dễ hiểu nhầm là tim của đứa bé; đổi chủ thể rõ hơn.',
  },
  {
    id: 'batch-signing-like-skin-cut',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Việc\s+ký\s+ấy\s+như\s+một\s+miếng\s+da\s+bị\s+rạch\s+ra/giu,
    replacement: 'Tôi ký, dù trong lòng nghẹn lại',
    message: 'Ẩn dụ “miếng da bị rạch” quá gượng; đổi thành phản ứng trực tiếp.',
  },
  {
    id: 'batch-face-holding-thing',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'template-replace',
    pattern: /gương\s+mặt\s+([^.!?\n]{1,30})\s+cầm\s+một\s+điều\s+dung\s+dị/giu,
    replacement: 'vẻ mặt $1 bình tĩnh lạ thường',
    message: '“Gương mặt cầm một điều” sai nghĩa; đổi thành biểu hiện cụ thể.',
  },
  {
    id: 'batch-print-machine-feeling-room',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /Đám\s+in\s+chạy\s+lạch\s+cạch\s+như\s+đang\s+cố\s+kìm\s+cảm\s+giác\s+trong\s+phòng/giu,
    replacement: 'Máy in chạy lạch cạch, làm căn phòng càng thêm căng',
    message: '“Đám in” và “kìm cảm giác” sai/tối nghĩa; đổi thành cảnh cụ thể.',
  },
  {
    id: 'batch-work-with-tea-wrong-phrase',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /về\s+nhà\s+làm\s+việc\s+với\s+tôi\s+một\s+cốc\s+trà/giu,
    replacement: 'gặp tôi nói chuyện một lát',
    message: '“Làm việc với tôi một cốc trà” sai diễn đạt; đổi thành hành động rõ.',
  },
  {
    id: 'batch-light-mix-table',
    category: 'collocation',
    severity: 'medium',
    mode: 'replace',
    pattern: /ánh\s+đèn\s+huỳnh\s+quang\s+pha\s+vào\s+mặt\s+bàn\s+gỗ/giu,
    replacement: 'ánh đèn huỳnh quang hắt xuống mặt bàn gỗ',
    message: '“Ánh đèn pha vào mặt bàn” sai tai; đổi thành “hắt xuống”.',
  },
  {
    id: 'batch-two-sentences-door-hit-face',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /Hai\s+câu\s+ngắn\s+mà\s+như\s+giáng\s+thêm\s+một\s+cánh\s+cửa\s+đóng\s+vào\s+mặt\s+tôi/giu,
    replacement: 'Hai câu ngắn đủ khiến lòng tôi chùng xuống',
    message: 'Ẩn dụ “giáng thêm một cánh cửa đóng vào mặt” rối và gượng.',
  },
  {
    id: 'batch-suit-like-needle',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /áo\s+vest\s+như\s+kim/giu,
    replacement: 'áo vest phẳng phiu',
    message: '“Áo vest như kim” tối nghĩa; đổi thành mô tả trực tiếp.',
  },
  {
    id: 'batch-eyes-shoot-look',
    category: 'collocation',
    severity: 'high',
    mode: 'replace',
    pattern: /phóng\s+mắt\s+nhìn/giu,
    replacement: 'nheo mắt nhìn kỹ',
    message: '“Phóng mắt nhìn” sai collocation trong ngữ cảnh này.',
  },
  {
    id: 'batch-building-court-typo',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /ban\s+quản\s+lý\s+tòa\s+án\s+lâm/giu,
    replacement: 'ban quản lý tòa nhà',
    message: 'Sửa cụm sai “ban quản lý tòa án lâm” thành “ban quản lý tòa nhà”.',
  },
  {
    id: 'batch-business-area-typo',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /khu\s+danh\s+nghiệp/giu,
    replacement: 'khu văn phòng',
    message: 'Sửa cụm sai “khu danh nghiệp”.',
  },
  {
    id: 'batch-enough-open-door',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Nó\s+có\s+đủ\s+để\s+mở\s+một\s+cửa/giu,
    replacement: 'Nó đủ để tôi lần tiếp',
    message: '“Mở một cửa” hơi AI và cụt nghĩa; đổi thành ý điều tra rõ hơn.',
  },
  {
    id: 'batch-heart-empty-choice',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Lòng\s+([^.!?\n]{1,20})\s+trống\s+rỗng\s+như\s+thể\s+đã\s+lựa\s+chọn\s+đường\s+đi/giu,
    replacement: '$1 nhìn tôi, sắc mặt trắng bệch như vừa quyết định xong',
    message: 'POV “tôi” không nên biết chắc lòng người khác; đổi thành biểu hiện bên ngoài.',
  },
  {
    id: 'batch-lawyer-wait-kick-power',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /dáng\s+vẻ\s+luật\s+sư\s+chờ\s+sút\s+quyền\s+lực/giu,
    replacement: 'dáng vẻ như một luật sư đang chờ xem cán cân nghiêng về phía nào',
    message: '“Chờ sút quyền lực” sai nghĩa; đổi thành hình ảnh dễ hiểu hơn.',
  },


  {
    id: 'batch3-stamp-smile-cut-metaphor',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /con\s+dấu\s+([^.!?\n]{0,80})\s+như\s+một\s+nụ\s+cười\s+bị\s+cắt/giu,
    replacement: 'con dấu $1, vệt mực bị hụt rõ ở một bên',
    message: 'Ẩn dụ “con dấu như nụ cười bị cắt” gượng; đổi thành dấu hiệu vật chứng cụ thể.',
  },
  {
    id: 'batch3-question-like-pin-heart',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /câu\s+hỏi\s+như\s+cái\s+ghim\s+vào\s+tim/giu,
    replacement: 'câu hỏi ấy khiến tôi khựng lại',
    message: 'Ẩn dụ “cái ghim vào tim” sáo và lộ AI; đổi thành phản ứng trực tiếp.',
  },
  {
    id: 'batch3-turn-into-another-page',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'replace',
    pattern: /có\s+thể\s+làm\s+sang\s+trang\s+khác\s+hoàn\s+toàn/giu,
    replacement: 'có thể biến nó thành một văn bản khác hoàn toàn',
    message: '“Làm sang trang khác” tối nghĩa; đổi thành hậu quả pháp lý/văn bản rõ hơn.',
  },
  {
    id: 'batch3-room-held-breath',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'replace',
    pattern: /mọi\s+thứ\s+trong\s+phòng\s+như\s+nín\s+thở/giu,
    replacement: 'cả phòng im hẳn đi',
    message: '“Mọi thứ trong phòng nín thở” hơi văn/AI; đổi thành phản ứng cụ thể.',
  },
  {
    id: 'batch3-sentence-like-subtle-trap',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Câu\s+nói\s+như\s+một\s+cái\s+bẫy\s+tinh\s+tế/giu,
    replacement: 'Câu đó đủ để kéo dài thêm vài phút',
    message: 'Ẩn dụ “cái bẫy tinh tế” giải thích quá tay; đổi thành mục đích hành động rõ.',
  },
  {
    id: 'batch3-face-twisted-unclear',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /mặt\s+([^.!?\n]{0,30})\s*xoáy\s+lại\s+như\s+vừa\s+thoáng\s+nhận\s+ra\s+điều\s+gì/giu,
    replacement: 'sắc mặt $1 thay đổi như vừa nhận ra điều gì',
    message: '“Mặt xoáy lại” sai cảm giác; đổi thành biểu hiện bên ngoài tự nhiên hơn.',
  },
  {
    id: 'batch3-short-cold-mirror',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Câu\s+nói\s+ngắn,\s*lạnh,\s*như\s+một\s+tấm\s+gương:\s*ít\s+lời,\s*nhiều\s+ý/giu,
    replacement: 'Câu nói ngắn, lạnh, đủ để mọi người hiểu tôi sẽ không ký',
    message: 'Ẩn dụ “tấm gương” và giải thích “ít lời, nhiều ý” lộ AI; đổi thành tác động cụ thể.',
  },
  {
    id: 'batch3-glass-shard-in-head',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /nằm\s+trong\s+đầu\s+tôi\s+như\s+một\s+mảnh\s+kính\s+vỡ/giu,
    replacement: 'vẫn khiến tôi bứt rứt không yên',
    message: 'Ẩn dụ “mảnh kính vỡ trong đầu” nặng và lộ AI; đổi thành cảm giác trực tiếp.',
  },
  {
    id: 'batch3-music-like-breathing',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /tiếng\s+nhạc\s+nền\s+bị\s+bật\s+thấp\s+đến\s+mức\s+nghe\s+thành\s+tiếng\s+thở\s+đều/giu,
    replacement: 'tiếng nhạc nền bật rất nhỏ',
    message: '“Nhạc nền nghe thành tiếng thở đều” gượng; đổi thành mô tả đời hơn.',
  },
  {
    id: 'batch3-docx-water-cold-head',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'replace',
    pattern: /đầu\s+óc\s+tôi\s+như\s+có\s+ai\s+đổ\s+nước\s+lạnh/giu,
    replacement: 'đầu tôi lạnh đi',
    message: 'Ẩn dụ “đổ nước lạnh vào đầu” hơi sáo; đổi thành phản ứng ngắn gọn.',
  },
  {
    id: 'batch3-words-loaded-bullets',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /họ\s+đã\s+nạp\s+vào\s+nòng\s+những\s+viên\s+đạn\s+được\s+bắn\s+thẳng\s+vào\s+tôi/giu,
    replacement: 'họ đã chuẩn bị sẵn những câu chữ để đẩy tôi vào thế xấu',
    message: 'Ẩn dụ súng đạn quá đà; đổi thành hành động truyền thông cụ thể.',
  },
  {
    id: 'batch3-answer-like-knife',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Câu\s+trả\s+lời\s+buông\s+ra\s+như\s+mũi\s+dao/giu,
    replacement: 'Câu trả lời ấy khiến cả chỗ im đi',
    message: 'Ẩn dụ “mũi dao” sáo; đổi thành phản ứng cụ thể của đám đông.',
  },
  {
    id: 'batch3-key-opens-door-metaphor',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Dòng\s+đó\s+như\s+một\s+mấu\s+chốt\s+bật\s+mở\s+cánh\s+cửa/giu,
    replacement: 'Dòng đó cho tôi điểm để lần tiếp',
    message: 'Ẩn dụ “mấu chốt mở cửa” hơi AI; đổi thành tiến triển điều tra rõ.',
  },
  {
    id: 'batch3-line-like-needle',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Dòng\s+chữ\s+cuối\s+cùng\s+hiện\s+lên\s+như\s+một\s+mũi\s+kim/giu,
    replacement: 'Dòng chữ cuối cùng khiến tôi nhìn thẳng về phía người liên quan',
    message: 'Ẩn dụ “mũi kim” sáo; đổi thành hành động/đối tượng cụ thể.',
  },
  {
    id: 'batch3-thiep-lap-typo',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /thiếp\s+lập\s+dư\s+luận/giu,
    replacement: 'thiết lập dư luận',
    message: 'Sửa lỗi typo “thiếp lập” thành “thiết lập”.',
  },


  {
    id: 'batch4-smile-like-fox-wrong-phrase',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /cười\s+như\s+lừa/giu,
    replacement: 'cười nhạt',
    message: '“Cười như lừa” sai cảm giác trong truyện drama; đổi thành biểu hiện trực tiếp.',
  },
  {
    id: 'batch4-voice-like-thin-knife',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Giọng\s+([^.!?\n]{1,40})\s+như\s+dao\s+mỏng/giu,
    replacement: 'Giọng $1 lạnh và sắc',
    message: 'Ẩn dụ “giọng như dao mỏng” hơi gượng; đổi thành mô tả trực tiếp.',
  },
  {
    id: 'batch4-eyes-swarm-like-bees',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /ánh\s+mắt\s+mọi\s+người\s+đã\s+quần\s+lại\s+như\s+đàn\s+ong/giu,
    replacement: 'ánh mắt mọi người lập tức dồn về phía tôi',
    message: '“Ánh mắt quần lại như đàn ong” tối nghĩa và lộ AI; đổi thành áp lực đám đông cụ thể.',
  },
  {
    id: 'batch4-smile-letter-o',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /mỉm\s+cười\s+chữ\s+O/giu,
    replacement: 'mỉm cười đầy ẩn ý',
    message: '“Mỉm cười chữ O” sai/tối nghĩa trong tiếng Việt; đổi thành biểu hiện dễ hiểu.',
  },
  {
    id: 'batch4-crowd-tich-di',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /Đám\s+đông\s+tịch\s+đi/giu,
    replacement: 'Đám đông im hẳn đi',
    message: '“Tịch đi” sai tai; đổi thành “im hẳn đi”.',
  },
  {
    id: 'batch4-volume-down-octave',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'replace',
    pattern: /âm\s+lượng\s+trao\s+đổi\s+trong\s+phòng\s+hạ\s+thấp\s+xuống\s+một\s+octave/giu,
    replacement: 'tiếng xì xào trong phòng nhỏ hẳn xuống',
    message: 'Cụm “hạ xuống một octave” quá kỹ thuật và lộ AI; đổi thành phản ứng nghe được.',
  },
  {
    id: 'batch4-hand-wrap-object',
    category: 'collocation',
    severity: 'medium',
    mode: 'replace',
    pattern: /Tay\s+tôi\s+quấn\s+lấy\s+nó/giu,
    replacement: 'Tôi giữ chặt nó trong tay',
    message: '“Tay tôi quấn lấy nó” sai collocation; đổi thành hành động rõ.',
  },
  {
    id: 'batch4-face-turns-withered',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'replace',
    pattern: /mặt\s+([^.!?\n]{1,40})\s+úa\s+đi\s+trong\s+chốc\s+lát/giu,
    replacement: 'sắc mặt $1 thay đổi trong chốc lát',
    message: '“Mặt úa đi” gượng và hơi sai sắc thái; đổi thành biểu hiện trung tính.',
  },
  {
    id: 'batch4-eyes-slither-between-people',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /ánh\s+mắt\s+([^.!?\n]{1,40})\s+lươn\s+lẹo\s+giữa\s+([^.!?\n]{1,80})/giu,
    replacement: 'ánh mắt $1 đảo qua $2',
    message: '“Ánh mắt lươn lẹo” quá gượng; đổi thành hành động nhìn cụ thể.',
  },
  {
    id: 'batch4-message-stone-lake-ripples',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Tin\s+nhắn\s+đó\s+như\s+hòn\s+đá\s+thả\s+xuống\s+hồ,?\s*tạo\s+ra\s+mấy\s+vòng\s+sóng/giu,
    replacement: 'Tin nhắn đó khiến vài người trong phòng đổi sắc mặt',
    message: 'Ẩn dụ hòn đá/vòng sóng khá AI; đổi thành phản ứng cụ thể của người trong phòng.',
  },
  {
    id: 'batch4-world-shrinks-wrung-towel',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /thế\s+giới\s+của\s+tôi\s+co\s+lại\s+như\s+khăn\s+bị\s+vắt/giu,
    replacement: 'tôi thấy ngực mình thắt lại',
    message: 'Ẩn dụ “thế giới co như khăn bị vắt” kỳ và lộ AI; đổi thành phản ứng cơ thể đơn giản.',
  },
  {
    id: 'batch4-life-throws-pebble',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /đời\s+ném\s+thêm\s+viên\s+sỏi\s+khác/giu,
    replacement: 'lại có thêm một chuyện xảy ra',
    message: 'Ẩn dụ “đời ném viên sỏi” văn vẻ và làm chậm nhịp; đổi thành thông tin trực tiếp.',
  },
  {
    id: 'batch4-question-mark-climbs-up',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Một\s+dấu\s+hỏi\s+lớn\s+chồm\s+lên/giu,
    replacement: 'Tôi lập tức thấy có vấn đề',
    message: '“Dấu hỏi chồm lên” gượng; đổi thành nhận thức trực tiếp.',
  },
  {
    id: 'batch4-voice-cool-like-ice-cream',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Giọng\s+([^.!?\n]{1,40})\s+mát\s+như\s+kem/giu,
    replacement: 'Giọng $1 bình thản đến khó chịu',
    message: '“Giọng mát như kem” sai cảm giác trong cảnh đối chất; đổi thành thái độ rõ.',
  },
  {
    id: 'batch4-child-as-chair-support',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /dùng\s+con\s+làm\s+miếng\s+ghế\s+đỡ/giu,
    replacement: 'lôi con tôi ra làm điểm gây sức ép',
    message: '“Miếng ghế đỡ” tối nghĩa; đổi thành ý gây áp lực bằng đứa trẻ.',
  },
  {
    id: 'batch4-gallery-paintings-draw-me',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /cảm\s+giác\s+như\s+đang\s+đi\s+giữa\s+một\s+cuộc\s+triển\s+lãm\s+mà\s+mọi\s+bức\s+tranh\s+đều\s+vẽ\s+hình\s+tôi/giu,
    replacement: 'cảm giác như mọi ánh mắt trong showroom đều đang nhìn tôi',
    message: 'Ẩn dụ triển lãm/bức tranh quá văn và dài; đổi thành áp lực đám đông cụ thể.',
  },
  {
    id: 'batch4-hand-carved-path',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /tay\s+ai\s+đó\s+đã\s+rạch\s+đường\s+dẫn\s+thẳng\s+vào\s+đó/giu,
    replacement: 'ai đó đã cố tình dẫn mọi chuyện tới đó',
    message: 'Ẩn dụ “rạch đường dẫn” gượng; đổi thành hành động âm mưu rõ.',
  },

]

export const userVietnameseProseWarningRules: VietnameseProseRule[] = [
  {
    id: 'user-warning-meta-recap-inside-chapter',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'warning',
    pattern: /Hai câu tóm tắt nhanh|Tóm tắt nhanh|Ở chương trước|Nhắc lại một chút/gi,
    message: 'Lộ lời nhắc/tóm tắt meta trong bản đọc, làm truyện mất tự nhiên và rất giống AI.',
    genericSuggestion: 'Xóa câu meta, chuyển thông tin cần nhắc vào hành động hoặc lời thoại tự nhiên.',
  },
  {
    id: 'user-warning-too-many-toi-openings',
    category: 'unclear_sentence',
    severity: 'low',
    mode: 'warning',
    pattern: /(?:^|\n)(?:Tôi\s+[^.!?\n]+[.!?]\s*){3,}/g,
    message: 'Nhiều câu liên tiếp bắt đầu bằng “Tôi”, dễ làm nhịp văn đều và máy.',
    genericSuggestion: 'Đổi một vài câu sang mở đầu bằng hành động, bối cảnh, hoặc phản ứng của người khác.',
  },
  {
    id: 'user-warning-administrative-dialogue',
    category: 'dialogue_role',
    severity: 'low',
    mode: 'warning',
    pattern: /triệu tập họp phụ huynh khẩn|ở lại để làm rõ|xử lý nghiêm/gi,
    message: 'Một số câu thoại hơi hành chính/sạch quá, nên làm đời hơn theo vai nói.',
    genericSuggestion: 'Thêm vai xưng hô cụ thể: “Mọi người bình tĩnh”, “phiền cô ở lại để đối chiếu...”, “nhà trường sẽ kiểm tra ngay”.',
  },
  {
    id: 'user-warning-evidence-as-heavy-object',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'warning',
    pattern: /như\s+một\s+(?:viên\s+đá|hòn\s+đá|khối\s+đá)/gi,
    message: 'So sánh vật chứng/cảm xúc với đá thường làm câu nặng và AI.',
    genericSuggestion: 'Đổi thành hành động cụ thể: giữ chặt, cất vào túi, đặt lên bàn, không để ai chạm vào.',
  },
  {
    id: 'user-warning-showbiz-poster-metaphors',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'warning',
    pattern: /ván\s+bài|vệt\s+đen\s+giữa\s+ánh\s+sáng|tấm\s+bẫy|bật\s+công\s+tắc|cục\s+đá\s+xuống\s+giữa\s+không\s+khí/giu,
    message: 'Cụm ẩn dụ kiểu poster/sân khấu hóa còn mùi AI.',
    genericSuggestion: 'Đổi thành hành động hoặc phản ứng cụ thể: ai im lại, ai nhìn sang, ai cầm giấy, ai bước vào.',
  },
  {
    id: 'user-warning-truth-light-metaphor',
    category: 'slogan',
    severity: 'medium',
    mode: 'warning',
    pattern: /sự\s+thật\s+hé\s+ra|kéo\s+[^.!?\n]{2,80}\s+vào\s+ánh\s+sáng|khe\s+hở\s+để\s+bám\s+vào/giu,
    message: 'Cụm “sự thật hé ra/kéo vào ánh sáng/khe hở” là câu tổng kết AI.',
    genericSuggestion: 'Viết cụ thể nhân vật phát hiện gì, giữ vật chứng gì, sẽ hỏi ai hoặc kiểm tra ở đâu.',
  },
  {
    id: 'user-warning-countdown-ending',
    category: 'slogan',
    severity: 'medium',
    mode: 'warning',
    pattern: /bắt\s+đầu\s+đếm\s+ngược|đây\s+mới\s+chỉ\s+là\s+bước\s+đầu|chuyện\s+này\s+chưa\s+dừng\s+ở\s+đây/giu,
    message: 'Câu kết kiểu countdown/bước đầu dễ thành slogan.',
    genericSuggestion: 'Kết bằng dữ kiện cụ thể: tin nhắn, người xuất hiện, vật chứng mới, thời hạn rõ, hoặc hành động tiếp theo.',
  },


  {
    id: 'market-warning-soft-bun-metaphor',
    category: 'convert_phrase',
    severity: 'low',
    mode: 'warning',
    pattern: /bánh\s+bao\s+mềm/giu,
    message: 'Cụm convert viral, có thể giữ nếu đúng nhịp truyện mạng; tránh dùng quá nhiều.',
    genericSuggestion: 'Nếu muốn tự nhiên hơn: “người dễ bị bắt nạt”.',
  },
  {
    id: 'market-warning-defense-line-collapse',
    category: 'convert_phrase',
    severity: 'low',
    mode: 'warning',
    pattern: /tuyến\s+phòng\s+thủ\s+cuối\s+cùng\s+trong\s+lòng\s+tôi\s+(cũng\s+)?sụp\s+đổ/giu,
    message: 'Cụm convert drama phổ biến; có thể giữ nếu là cao trào cảm xúc.',
    genericSuggestion: 'Nếu muốn tự nhiên hơn: “tôi hoàn toàn chết lặng”.',
  },
  {
    id: 'market-warning-family-cutoff-idiom',
    category: 'convert_phrase',
    severity: 'low',
    mode: 'warning',
    pattern: /nước\s+sông\s+không\s+phạm\s+nước\s+giếng|người\s+dưng\s+nước\s+lã/giu,
    message: 'Cụm thành ngữ/convert dùng được trong đoạn cắt đứt quan hệ; không cần auto sửa.',
    genericSuggestion: 'Chỉ cảnh báo nếu lặp quá nhiều trong cùng chương.',
  },
  {
    id: 'market-warning-possible-name-typo-after-title',
    category: 'unclear_sentence',
    severity: 'low',
    mode: 'warning',
    pattern: /\b(Bà|Ông|Cô|Anh|Chị)\s+[A-Z][a-z]{2,}\b/gu,
    message: 'Có thể có typo tên riêng sau danh xưng; kiểm tra nếu tên bị lệch dấu hoặc lệch chữ.',
    genericSuggestion: 'Không auto sửa tên riêng. Chỉ cảnh báo để admin kiểm tra.',
  },


  {
    id: 'batch-warning-voice-like-hammer-fall',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'warning',
    pattern: /Tiếng\s+[^.!?\n]{1,30}\s+như\s+cái\s+búa\s+rơi\s+xuống|Câu\s+nói\s+như\s+búa\s+gõ/giu,
    message: 'Ẩn dụ búa gõ khá sáo; có thể giữ nếu là cao trào nhưng tránh dùng lặp.',
    genericSuggestion: 'Có thể đổi thành phản ứng cụ thể: cả phòng im đi, ai đó ngừng nói, người đối diện biến sắc.',
  },
  {
    id: 'batch-warning-reporters-waiting-blood',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'warning',
    pattern: /phóng\s+viên\s+[^.!?\n]{0,30}\s+như\s+chờ\s+máu/giu,
    message: '“Phóng viên như chờ máu” hơi nặng và lộ AI; cân nhắc đổi sang hành động săn tin cụ thể.',
    genericSuggestion: 'Ví dụ: “phóng viên im thin thít, chỉ chờ một câu có thể cắt thành tiêu đề.”',
  },
  {
    id: 'batch-warning-honor-chopped-public',
    category: 'convert_phrase',
    severity: 'low',
    mode: 'warning',
    pattern: /danh\s+dự\s+[^.!?\n]{0,30}\s+bị\s+băm\s+nhỏ/giu,
    message: 'Cụm này rất drama/convert; có thể giữ nếu hợp gu truyện mạng, nhưng tránh lặp.',
  },


  {
    id: 'batch3-warning-private-room-courtroom',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'warning',
    pattern: /ánh\s+đèn\s+ấm\s+[^.!?\n]{0,80}\s+phòng\s+xử\s+án/giu,
    message: 'So sánh không gian gia đình/ký kết với phòng xử án dùng được nhưng dễ sáo nếu lặp.',
    genericSuggestion: 'Có thể đổi thành áp lực cụ thể: ai ngồi đâu, giấy tờ đặt thế nào, ai chờ ký.',
  },
  {
    id: 'batch3-warning-add-fire-voice',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'warning',
    pattern: /Giọng\s+[^.!?\n]{0,40}\s+như\s+thổi\s+thêm\s+lửa/giu,
    message: '“Giọng như thổi thêm lửa” khá sáo; có thể giữ nếu đúng nhịp nhưng tránh lặp.',
    genericSuggestion: 'Đổi thành phản ứng cụ thể: đám đông xì xào lớn hơn, người bị ép biến sắc.',
  },
  {
    id: 'batch3-warning-cold-short-voice',
    category: 'convert_phrase',
    severity: 'low',
    mode: 'warning',
    pattern: /giọng\s+(?:ngắn|lạnh|sắc)|bật\s+cười\s+lạnh/giu,
    message: 'Cụm giọng lạnh/bật cười lạnh hợp truyện mạng, nhưng dễ lặp nếu xuất hiện nhiều trong một chương.',
  },
  {
    id: 'batch3-warning-public-pr-strategy-line',
    category: 'slogan',
    severity: 'medium',
    mode: 'warning',
    pattern: /không\s+phải\s+mấy\s+chiêu\s+trò\s+PR|chịu\s+trách\s+nhiệm\s+trước\s+mặt\s+tất\s+cả/giu,
    message: 'Câu tuyên bố hơi khẩu hiệu; có thể giữ ở cao trào nhưng nên ưu tiên hành động cụ thể đi kèm.',
    genericSuggestion: 'Cho nhân vật yêu cầu niêm phong file, giữ chìa khóa, mở metadata, hoặc gọi người chịu trách nhiệm ra đối chất.',
  },


  {
    id: 'batch4-warning-family-table-theater',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'warning',
    pattern: /ngồi\s+im\s+như\s+chờ\s+màn\s+kịch\s+bắt\s+đầu|màn\s+kịch\s+bắt\s+đầu/giu,
    message: 'So sánh cảnh gia đình với “màn kịch” dùng được nhưng dễ sáo nếu lặp nhiều.',
    genericSuggestion: 'Có thể chuyển sang hành động cụ thể: ai nhìn ai, ai đặt giấy/tách/cốc ở đâu, ai ép nói trước.',
  },
  {
    id: 'batch4-warning-cold-sharp-voice-repeat',
    category: 'convert_phrase',
    severity: 'low',
    mode: 'warning',
    pattern: /giọng\s+(?:bình\s+tĩnh\s+nhưng\s+rất\s+sắc|lịch\s+sự\s+nhưng\s+mắt\s+né)|nhếch\s+môi|bật\s+cười\s+nhẹ/giu,
    message: 'Cụm giọng sắc/nhếch môi/bật cười nhẹ hợp truyện mạng nhưng dễ lặp; chỉ nên dùng khi đúng cao trào.',
  },
  {
    id: 'batch4-warning-object-as-evidence-summary',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'warning',
    pattern: /mảnh\s+bằng\s+chứng\s+nhỏ|khe\s+hở\s+đầu\s+tiên|kim\s+chỉ\s+nam/giu,
    message: 'Cụm tổng kết bằng chứng kiểu “mảnh nhỏ/khe hở/kim chỉ nam” đọc được nhưng dễ thành giọng AI nếu lặp.',
    genericSuggestion: 'Ưu tiên viết bằng chứng cụ thể là gì và nhân vật sẽ dùng nó để hỏi/đối chiếu với ai.',
  },


  // Batch 5: rules từ truyện nhẫn mã khắc + thẻ ra vào/quẹt thẻ/locker
  {
    id: 'batch5-sweat-on-collar-hand',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'replace',
    pattern: /tay\s+còn\s+dính\s+vệt\s+mồ\s+hôi\s+nơi\s+cổ\s+áo/giu,
    replacement: 'cổ áo vẫn còn vệt mồ hôi lạnh',
    message: 'Câu “tay dính vệt mồ hôi nơi cổ áo” sai hình ảnh; đổi chủ thể rõ hơn.',
  },
  {
    id: 'batch5-cut-air-entry',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /bước\s+lên\s+trước\s+như\s+muốn\s+cắt\s+không\s+khí/giu,
    replacement: 'bước lên trước, cắt ngang bầu không khí nặng nề',
    message: '“Cắt không khí” hơi gượng; đổi thành hành động rõ hơn.',
  },
  {
    id: 'batch5-short-cut-voice',
    category: 'collocation',
    severity: 'medium',
    mode: 'replace',
    pattern: /giọng\s+cắt(?=[\s:,.!?])/giu,
    replacement: 'giọng sắc lạnh',
    message: '“Giọng cắt” cụt và hơi dịch; đổi thành “giọng sắc lạnh”.',
  },
  {
    id: 'batch5-fit-into-ready-answer',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /như\s+muốn\s+nhét\s+tôi\s+vào\s+một\s+câu\s+trả\s+lời\s+có\s+sẵn/giu,
    replacement: 'như đã định sẵn tôi phải nhận lỗi',
    message: 'Ẩn dụ “nhét vào câu trả lời” gượng; đổi thành ý rõ.',
  },
  {
    id: 'batch5-voice-like-want-kill',
    category: 'convert_phrase',
    severity: 'medium',
    mode: 'replace',
    pattern: /giọng\s+như\s+muốn\s+giết\s+người/giu,
    replacement: 'giọng ép sát từng chữ',
    message: '“Giọng như muốn giết người” quá nặng và hơi thô; đổi thành áp lực lời nói rõ hơn.',
  },
  {
    id: 'batch5-eyes-like-small-needle',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /ánh\s+mắt\s+([^.!?\n]{1,40})\s+như\s+một\s+mũi\s+kim\s+nhỏ/giu,
    replacement: '$1 căng thẳng nhưng vẫn giữ im lặng',
    message: 'Ẩn dụ “ánh mắt như mũi kim nhỏ” hơi AI; đổi thành trạng thái rõ.',
  },
  {
    id: 'batch5-silent-flow',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'replace',
    pattern: /Một\s+luồng\s+im\s+lặng/giu,
    replacement: 'Cả phòng im hẳn đi',
    message: '“Một luồng im lặng” cụt và dịch; đổi thành phản ứng rõ.',
  },
  {
    id: 'batch5-cut-speaking-air',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /cắt\s+mất\s+cho\s+tôi\s+không\s+khí\s+được\s+nói/giu,
    replacement: 'tước mất quyền lên tiếng của tôi',
    message: 'Cụm “không khí được nói” tối nghĩa; đổi thành ý trực tiếp.',
  },
  {
    id: 'batch5-hold-remaining-piece-right-lost',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'replace',
    pattern: /Tôi\s+ôm\s+lấy\s+mảnh\s+ghép\s+còn\s+lại:\s*quyền\s+bị\s+tước/giu,
    replacement: 'Tôi hiểu mình vừa mất một quyền quan trọng',
    message: 'Câu “ôm lấy mảnh ghép còn lại: quyền bị tước” văn nhưng gượng; đổi thành ý rõ.',
  },
  {
    id: 'batch5-eye-pour-red',
    category: 'collocation',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /mắt\s+([^.!?\n]{0,20})\s*đổ\s+đỏ/giu,
    replacement: 'mắt $1 đỏ lên',
    message: '“Mắt đổ đỏ” sai collocation; đổi thành “đỏ lên”.',
  },
  {
    id: 'batch5-ceiling-light-closed-space',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'replace',
    pattern: /Đèn\s+trên\s+trần\s+tạo\s+một\s+khoảng\s+sáng\s+khép\s+kín/giu,
    replacement: 'Ánh đèn trần phủ xuống bàn họp, làm căn phòng càng ngột ngạt',
    message: 'Câu tả ánh sáng hơi mơ hồ; đổi thành không khí cảnh rõ hơn.',
  },
  {
    id: 'batch5-touch-arrow-guide',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'warning',
    pattern: /như\s+sờ\s+vào\s+mũi\s+tên\s+chỉ\s+đường/giu,
    message: 'Ẩn dụ “sờ vào mũi tên chỉ đường” hơi AI; có thể đổi thành “chạm được vào một đầu mối rõ ràng”.',
    genericSuggestion: 'như vừa chạm được vào một đầu mối rõ ràng.',
  },
  {
    id: 'batch5-slipper-mut-floor',
    category: 'collocation',
    severity: 'medium',
    mode: 'replace',
    pattern: /tiếng\s+dép\s+mút\s+trên\s+sàn\s+nhựa/giu,
    replacement: 'tiếng dép cao su lẹp xẹp trên sàn nhựa',
    message: '“Dép mút” không tự nhiên trong cảnh sàn nhựa; đổi thành “dép cao su”.',
  },
  {
    id: 'batch5-voice-point-at-me',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /giọng\s+([^.!?\n]{1,40})\s+như\s+chĩa\s+thẳng\s+về\s+tôi/giu,
    replacement: 'giọng $1 nhắm thẳng vào tôi',
    message: '“Giọng chĩa thẳng” gượng; đổi thành “nhắm thẳng vào tôi”.',
  },
  {
    id: 'batch5-voice-point-wound',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /giọng\s+như\s+chĩa\s+vào\s+vết\s+thương/giu,
    replacement: 'giọng anh ta lạnh và ác ý',
    message: 'Ẩn dụ “giọng chĩa vào vết thương” hơi quá; đổi thành thái độ cụ thể.',
  },
  {
    id: 'batch5-a-an-typo',
    category: 'typo',
    severity: 'high',
    mode: 'replace',
    pattern: /tiếng\s+a-an\s+kia/giu,
    replacement: 'tiếng xì xào kia',
    message: 'Sửa lỗi chữ “a-an” thành “xì xào”.',
  },
  {
    id: 'batch5-not-pout-serious-scene',
    category: 'collocation',
    severity: 'medium',
    mode: 'replace',
    pattern: /Tôi\s+không\s+xụ\s+mặt/giu,
    replacement: 'Tôi không để lộ vẻ hoảng loạn',
    message: '“Xụ mặt” quá trẻ con trong cảnh nghiêm trọng; đổi thành phản ứng phù hợp hơn.',
  },
  {
    id: 'batch5-secret-in-heart-clue',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /đó\s+là\s+một\s+mảnh\s+mà\s+tôi\s+giấu\s+trong\s+tim/giu,
    replacement: 'đó vẫn là một manh mối tôi cần giữ lại',
    message: '“Giấu trong tim” không hợp khi đang nói manh mối; đổi thành ý điều tra rõ.',
  },
  {
    id: 'batch5-process-paused',
    category: 'collocation',
    severity: 'medium',
    mode: 'replace',
    pattern: /quá\s+trình\s+bị\s+tạm\s+hoãn/giu,
    replacement: 'lời buộc tội đã bị chặn lại',
    message: '“Quá trình bị tạm hoãn” hơi hành chính; đổi thành tác động cụ thể trong cảnh đối chất.',
  },
  {
    id: 'batch5-eyes-stop-on-object',
    category: 'collocation',
    severity: 'medium',
    mode: 'replace',
    pattern: /mắt\s+([^.!?\n]{1,30})\s+dừng\s+ở\s+mép\s+thẻ\s+in/giu,
    replacement: 'ánh mắt $1 dừng trên mép thẻ trong ảnh',
    message: '“Mắt dừng” hơi dịch; đổi thành “ánh mắt dừng trên...”.',
  },
  {
    id: 'batch5-knife-ready-smile',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /([^.!?\n]{1,50})\s+cười\s+như\s+con\s+dao\s+đã\s+mài\s+sẵn/giu,
    replacement: '$1 cười nhạt, vẻ mặt như đã chuẩn bị sẵn đòn mới',
    message: 'Ẩn dụ “cười như con dao đã mài sẵn” lộ AI; đổi thành vẻ mặt và ý đồ cụ thể.',
  },
  {
    id: 'batch5-scissors-into-labor',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /Đình\s+chỉ\s+—\s*hai\s+từ\s+đó\s+như\s+lưỡi\s+kéo\s+vào\s+tiếng\s+lao\s+động\s+mấy\s+năm\s+tôi\s+bỏ\s+ra\s+cho\s+quỹ/giu,
    replacement: 'Hai chữ “đình chỉ” đủ khiến công sức mấy năm của tôi bị đặt dấu hỏi',
    message: 'Ẩn dụ “lưỡi kéo vào tiếng lao động” tối nghĩa; đổi thành ý rõ.',
  },
  {
    id: 'batch5-open-eyes-wrong-collocation',
    category: 'collocation',
    severity: 'medium',
    mode: 'replace',
    pattern: /Tống\s+Vân\s+mở\s+mắt/giu,
    replacement: 'Tống Vân khựng lại',
    message: '“Mở mắt” không tự nhiên trong ngữ cảnh đang quan sát; đổi thành phản ứng rõ.',
  },
  {
    id: 'batch5-bound-into-tightening',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /như\s+đã\s+buộc\s+tôi\s+vào\s+một\s+cú\s+siết/giu,
    replacement: 'như đã dồn được tôi vào thế bí',
    message: '“Buộc vào một cú siết” tối nghĩa; đổi thành “dồn vào thế bí”.',
  },
  {
    id: 'batch5-eyes-with-curiosity',
    category: 'collocation',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /mắt\s+([^.!?\n]{1,30})\s+kèm\s+một\s+tia\s+tò\s+mò/giu,
    replacement: 'trong mắt $1 lóe lên một tia tò mò',
    message: 'Sửa cấu trúc “mắt kèm một tia tò mò” thành cách nói tự nhiên.',
  },
  {
    id: 'batch5-chlech-re-khoi-ke-hoach',
    category: 'typo',
    severity: 'medium',
    mode: 'replace',
    pattern: /chệch\s+rẽ\s+khỏi\s+kế\s+hoạch/giu,
    replacement: 'chệch khỏi kế hoạch',
    message: 'Sửa cụm sai “chệch rẽ khỏi kế hoạch”.',
  },
  {
    id: 'batch5-temporary-silence',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'replace',
    pattern: /cuộc\s+im\s+lặng\s+tạm\s+bợ/giu,
    replacement: 'khoảng im lặng ngắn ngủi',
    message: '“Cuộc im lặng tạm bợ” gượng; đổi thành cụm tự nhiên hơn.',
  },
  {
    id: 'batch5-pencil-mark-thread',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'replace',
    pattern: /vết\s+chì\s+mờ\s+kia\s+là\s+đường\s+chỉ/giu,
    replacement: 'vết chì mờ kia là đầu mối',
    message: '“Đường chỉ” hơi văn; đổi thành “đầu mối” rõ hơn.',
  },
  {
    id: 'batch5-thick-atmosphere-warning',
    category: 'ai_metaphor',
    severity: 'low',
    mode: 'warning',
    pattern: /Bầu\s+không\s+khí\s+đặc\s+quánh/giu,
    message: 'Cụm này đọc được nhưng khá sáo; tránh lặp nhiều trong cùng batch.',
    genericSuggestion: 'Không khí trong phòng nặng hẳn xuống.',
  },
  {
    id: 'batch5-surrounded-circle-warning',
    category: 'convert_phrase',
    severity: 'low',
    mode: 'warning',
    pattern: /bị\s+kéo\s+vào\s+giữa\s+vòng\s+vây/giu,
    message: '“Bị kéo vào giữa vòng vây” hợp truyện mạng nhưng dễ sáo nếu lặp.',
  },


  {
    id: 'user-bad-opening-center-room-verdict',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /Tôi\s+đứng\s+ngay\s+giữa\s+([^,.!?\n]{2,80}),\s*([^.!?\n]{0,100})\s*(?:như\s+)?chờ\s+một\s+lời\s+tuyên\s+án/giu,
    replacement: (_match, captures) => {
      const place = captures[0]?.trim() || 'căn phòng'
      return `Tôi đứng giữa ${place}, biết mọi người đang chờ tôi giải thích`
    },
    message: 'Mở cảnh kiểu “chờ một lời tuyên án” bị sân khấu hóa; đổi thành áp lực trực tiếp, đời hơn.',
    genericSuggestion: 'Tôi đứng giữa [địa điểm], biết mọi người đang chờ tôi giải thích.',
  },
  {
    id: 'user-voice-like-knife-aimed',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /giọng\s+(?:anh ta|cô ta|hắn|bà ta|ông ta|[^,.!?\n]{1,30})\s+như\s+(?:chĩa|nhắm)\s+(?:thẳng\s+)?(?:vào|về)\s+([^.!?\n]{2,80})/giu,
    replacement: 'giọng người đó đủ lớn để mọi người quay sang nhìn $1',
    message: 'Cụm “giọng như chĩa vào...” là ẩn dụ AI; đổi thành tác động cụ thể lên đám đông.',
    genericSuggestion: 'Giọng người đó đủ lớn để mọi người quay sang nhìn [nhân vật/vật chứng].',
  },
  {
    id: 'user-object-as-arrow-direction',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /([^.!?\n]{2,120})\s+như\s+(?:một\s+)?mũi\s+tên\s+chỉ\s+đường/giu,
    replacement: '$1 là thứ tôi cần kiểm tra tiếp',
    message: 'Ẩn dụ “mũi tên chỉ đường” sáo; đổi thành ý kiểm tra tiếp cụ thể.',
    genericSuggestion: '[Vật chứng/chi tiết] là thứ tôi cần kiểm tra tiếp.',
  },
  {
    id: 'user-world-shrinks-like-towel',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /thế\s+giới\s+của\s+tôi\s+co\s+lại\s+như\s+khăn\s+bị\s+vắt/giu,
    replacement: 'tôi nghe mà ngực nghẹn lại',
    message: 'So sánh “thế giới co lại như khăn bị vắt” tối nghĩa/gượng; đổi thành phản ứng cơ thể rõ hơn.',
  },
  {
    id: 'user-exhibition-every-picture-me',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /cảm\s+giác\s+như\s+đang\s+đi\s+giữa\s+một\s+cuộc\s+triển\s+lãm\s+mà\s+mọi\s+bức\s+tranh\s+đều\s+vẽ\s+hình\s+tôi/giu,
    replacement: 'tôi cảm giác ai đi ngang cũng đang nhìn mình',
    message: 'Câu ví von triển lãm/vẽ hình tôi quá AI và tối nghĩa; đổi thành cảm giác bị nhìn rõ ràng.',
  },
  {
    id: 'user-pull-a-thread-from-past',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /kéo\s+vài\s+sợi\s+nhỏ\s+từ\s+quá\s+khứ\s+lên\s+mặt\s+bàn/giu,
    replacement: 'đưa vài chi tiết cũ ra trước mặt mọi người',
    message: 'Cụm “kéo sợi từ quá khứ lên mặt bàn” gượng; đổi thành hành động đưa chi tiết/bằng chứng ra.',
  },
  {
    id: 'user-silence-guards-room',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Đoạn\s+im\s+trấn\s+giữ\s+cả\s+căn\s+phòng\s+kéo\s+dài\s+vài\s+giây/giu,
    replacement: 'Căn phòng im vài giây liền',
    message: 'Cụm “đoạn im trấn giữ” làm văn quá tay; đổi thành câu ngắn rõ.',
  },
  {
    id: 'user-drop-stone-name-room',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /([^.!?\n]{1,60})\s+như\s+thả\s+một\s+hòn\s+đá\s+xuống\s+nước/giu,
    replacement: '$1 khiến căn phòng im đi',
    message: 'Ẩn dụ hòn đá xuống nước bị dùng quá nhiều; đổi thành phản ứng của căn phòng.',
  },
  {
    id: 'user-thing-has-been-cut-away-from-me',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /(?:họ|người ta)\s+vừa\s+cắt\s+mất\s+cho\s+tôi\s+([^.!?\n]{2,80})/giu,
    replacement: 'họ vừa tước mất của tôi $1',
    message: 'Cụm “cắt mất cho tôi” sai tai; đổi thành “tước mất của tôi”.',
  },
  {
    id: 'user-evidence-line-thread-path',
    category: 'slogan',
    severity: 'medium',
    mode: 'template-replace',
    pattern: /(?:đường\s+chỉ|dòng\s+chữ|vết\s+[^,.!?\n]{1,40})\s+(?:là|như)\s+(?:một\s+)?(?:đường\s+dẫn|móc\s+nối|đường\s+chỉ)\s*([^.!?\n]{0,80})/giu,
    replacement: 'Chi tiết đó là thứ tôi cần kiểm tra tiếp$1',
    message: 'Cụm “đường chỉ/đường dẫn/móc nối” tổng kết kiểu AI; đổi thành mục tiêu kiểm tra cụ thể.',
  },
    // Batch 8: cleanup câu convert/tối nghĩa từ truyện cũ.
  {
    id: 'market-smile-too-quiet',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'replace',
    pattern: /Anh\s+ta\s+nở\s+nụ\s+cười\s+hơi\s+quá\s+khẽ/giu,
    replacement: 'Anh ta cười rất nhẹ',
    message: 'Cụm “nở nụ cười hơi quá khẽ” gượng, không tự nhiên trong tiếng Việt.',
  },
  {
    id: 'market-i-agree-number',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'replace',
    pattern: /Tôi\s+đồng\s+ý,\s*mắt\s+không\s+rời\s+con\s+số/giu,
    replacement: 'Tôi gật đầu rất khẽ, mắt vẫn dính vào con số đó',
    message: '“Tôi đồng ý” dễ sai nghĩa khi nữ chính đang nghi ngờ biên nhận.',
  },
  {
    id: 'market-money-currency',
    category: 'convert_phrase',
    severity: 'high',
    mode: 'replace',
    pattern: /Chúng\s+ta\s+mất\s+tiền\s+tệ,\s*mất\s+dự\s+án/giu,
    replacement: 'Chúng ta mất tiền, mất cả dự án',
    message: '“Mất tiền tệ” là lỗi convert.',
  },
  {
    id: 'market-bell-throat',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /Hồi\s+chuông\s+cảm\s+thấy\s+đập\s+trong\s+cổ\s+họng\s+tôi/giu,
    replacement: 'Cổ họng tôi nghẹn lại như có thứ gì mắc ngang',
    message: 'Ẩn dụ sai chủ thể, tối nghĩa.',
  },
  {
    id: 'market-buoc-moi',
    category: 'convert_phrase',
    severity: 'high',
    mode: 'replace',
    pattern: /Tôi\s+buộc\s+môi/giu,
    replacement: 'Tôi mím môi',
    message: '“Buộc môi” không tự nhiên trong tiếng Việt.',
  },
  {
    id: 'market-too-late-careful-stage',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'replace',
    pattern: /Không\s+kịp\s+dè\s+chừng,\s*buổi\s+tối\s+nay\s+tôi\s+vẫn\s+phải\s+lên\s+sân\s+khấu/giu,
    replacement: 'Không còn thời gian dè chừng. Tối nay tôi vẫn phải lên sân khấu',
    message: 'Câu gãy, thiếu tự nhiên.',
  },
  {
    id: 'market-choc-mieng',
    category: 'convert_phrase',
    severity: 'high',
    mode: 'replace',
    pattern: /anh\s+ta\s+chọc\s+miệng/giu,
    replacement: 'anh ta mở lời',
    message: '“Chọc miệng” là cụm sai/convert.',
  },
  {
    id: 'market-to-cao-chung-cu',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /phải\s+gọn,\s*không\s+thể\s+lao\s+vào\s+tố\s+cáo\s+chung\s+cư/giu,
    replacement: 'phải gọn, không thể lao vào tố cáo lung tung',
    message: '“Tố cáo chung cư” sai nghĩa trong ngữ cảnh này.',
  },
  {
    id: 'market-tho-te-nhi',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /một\s+kế\s+hoạch\s+cả\s+cục\s+lẫn\s+tế\s+nhị/giu,
    replacement: 'một kế hoạch vừa thô vừa khéo',
    message: 'Cụm “cả cục lẫn tế nhị” gượng và khó hiểu.',
  },
  {
    id: 'market-hidden-account-link',
    category: 'unclear_sentence',
    severity: 'medium',
    mode: 'replace',
    pattern: /một\s+đường\s+link\s+nhỏ\s+hiện:\s*["“]tài\s+khoản\s+ẩn\s+—\s+không\s+công\s+khai["”]/giu,
    replacement: 'một dòng trạng thái hiện lên: “tài khoản riêng tư”',
    message: 'Mô tả UI thiếu tự nhiên.',
  },
  {
    id: 'market-moi-lua',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /như\s+một\s+mồi\s+lửa/giu,
    replacement: 'như một dấu vết chưa kịp bị xóa',
    message: 'Ẩn dụ “mồi lửa” hơi AI; đổi thành vật chứng cụ thể.',
  },
  {
    id: 'market-step-prepared',
    category: 'convert_phrase',
    severity: 'medium',
    mode: 'replace',
    pattern: /bước\s+chậm\s+như\s+đã\s+chuẩn\s+bị/giu,
    replacement: 'bước tới rất chậm, rõ ràng đã chuẩn bị sẵn',
    message: 'Câu “bước chậm như đã chuẩn bị” hơi dịch máy.',
  },
  {
    id: 'market-laptop-shout',
    category: 'tone_naturalness',
    severity: 'medium',
    mode: 'replace',
    pattern: /Tôi\s+kéo\s+laptop\s+ra\s+giữa\s+hậu\s+trường,\s*hét\s+lên\s+đủ\s+để\s+mấy\s+người\s+tổ\s+chức\s+quay\s+lại/giu,
    replacement: 'Tôi kéo laptop ra giữa hậu trường, nâng giọng đủ để mấy người tổ chức quay lại',
    message: '“Hét lên đủ” hơi thô và lệch hình tượng nữ chính bình tĩnh.',
  },
  {
    id: 'market-tieng-suoi-vo',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /tiếng\s+suối\s+vỡ/giu,
    replacement: 'giọng vỡ ra',
    message: 'Ẩn dụ “tiếng suối vỡ” sai/cứng.',
  },
  {
    id: 'market-chuyen-on-typo',
    category: 'typo',
    severity: 'high',
    mode: 'replace',
    pattern: /Chuyện\s+ơn\s+một\s+chút/giu,
    replacement: 'Chuyện ổn một chút rồi',
    message: 'Typo “ơn” → “ổn”.',
  },
  {
    id: 'market-yen-red-turn',
    category: 'word_order',
    severity: 'medium',
    mode: 'replace',
    pattern: /Yến\s+quay\s+người\s+đỏ\s+mặt/giu,
    replacement: 'Yến đỏ mặt, quay phắt đi',
    message: 'Trật tự từ gượng.',
  },
  {
    id: 'market-bong-mieng',
    category: 'convert_phrase',
    severity: 'high',
    mode: 'replace',
    pattern: /Không\s+thích\s+hợp\s+bỏng\s+miệng\s+gọi\s+ra/giu,
    replacement: 'Tôi không tiện gọi thẳng tên ở đây',
    message: 'Câu tối nghĩa, rất giống lỗi convert.',
  },
  {
    id: 'market-cuu-xet',
    category: 'convert_phrase',
    severity: 'high',
    mode: 'replace',
    pattern: /Cứu\s+xét,\s*tôi\s+không\s+làm\s+kịch/giu,
    replacement: 'Tôi không làm màu',
    message: '“Cứu xét” dùng sai hoàn toàn.',
  },
  {
    id: 'market-mui-dau-tin-xau',
    category: 'ai_metaphor',
    severity: 'high',
    mode: 'replace',
    pattern: /tôi\s+cảm\s+nhận\s+được\s+cái\s+mũi\s+đau\s+của\s+tin\s+xấu/giu,
    replacement: 'tôi cảm thấy tin xấu đang áp sát',
    message: 'Ẩn dụ tối nghĩa.',
  },
  {
    id: 'market-no-right-easy',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /Tôi\s+không\s+có\s+quyền\s+cho\s+việc\s+đó\s+dễ\s+dàng/giu,
    replacement: 'Tôi không có quyền xem chuyện đó là nhẹ',
    message: 'Câu gượng, khó hiểu.',
  },
    {
    id: 'market-typo-mo-xi-xao',
    category: 'typo',
    severity: 'high',
    mode: 'replace',
    pattern: /Mộ\s+tiếng\s+xì\s+xào\s+lan/giu,
    replacement: 'Một tiếng xì xào lan ra',
    message: 'Typo “Mộ” thành “Một”.',
  },
  {
    id: 'market-wrong-idiom-cuoi-ngua-xem-bay',
    category: 'convert_phrase',
    severity: 'high',
    mode: 'replace',
    pattern: /cố\s+cưỡi\s+ngựa\s+xem\s+bầy/giu,
    replacement: 'cố giữ vẻ bình tĩnh',
    message: 'Dùng sai thành ngữ; “cưỡi ngựa xem hoa” không hợp ngữ cảnh, còn “xem bầy” là lỗi.',
  },
  {
    id: 'market-khi-tranh-tro',
    category: 'unclear_sentence',
    severity: 'high',
    mode: 'replace',
    pattern: /khi\s+tranh\s+trò/giu,
    replacement: 'khi dỗ trẻ',
    message: 'Cụm “tranh trò” tối nghĩa, có vẻ lỗi sinh câu.',
  },
  {
    id: 'market-man-do',
    category: 'convert_phrase',
    severity: 'high',
    mode: 'replace',
    pattern: /Một\s+man\s+đỏ/giu,
    replacement: 'Một tờ tiền đỏ',
    message: '“Man đỏ” là lỗi convert/typo, không tự nhiên trong tiếng Việt.',
  },
  {
    id: 'market-attitude-understood-not-entered',
    category: 'ai_tone',
    severity: 'high',
    mode: 'replace',
    pattern: /một\s+thái\s+độ\s+cơ\s+bản:\s*hiểu\s+chuyện\s+nhưng\s+chưa\s+vào/giu,
    replacement: 'anh ta hiểu chuyện đã lộ, nhưng vẫn chưa dám bước vào',
    message: 'Câu phân tích khô, lộ giọng AI, không giống văn truyện.',
  },
  {
    id: 'market-duong-loi-di-tiep',
    category: 'collocation',
    severity: 'medium',
    mode: 'replace',
    pattern: /đó\s+là\s+đường\s+lối\s+đi\s+tiếp/giu,
    replacement: 'đó là hướng để tôi lần tiếp',
    message: '“Đường lối đi tiếp” gượng, giống văn hành chính.',
  },
  {
    id: 'market-outside-disable-account-fake',
    category: 'ai_tone',
    severity: 'medium',
    mode: 'replace',
    pattern: /không\s+phải\s+ai\s+đó\s+đứng\s+ngoài\s+vô\s+hiệu\s+hóa\s+tài\s+khoản\s+để\s+giả\s+mạo/giu,
    replacement: 'không phải người ngoài tùy tiện bấm máy là làm được',
    message: 'Câu kỹ thuật khô, làm mùi AI tăng.',
  },
  {
    id: 'market-compete-online-evidence',
    category: 'ai_tone',
    severity: 'high',
    mode: 'replace',
    pattern: /Họ\s+khóa\s+tài\s+khoản\s+của\s+tôi\s+để\s+tôi\s+không\s+thể\s+cạnh\s+tranh\s+bằng\s+chứng\s+trực\s+tuyến/giu,
    replacement: 'Họ khóa tài khoản để tôi không còn đường tự kiểm tra lịch đưa đón',
    message: '“Cạnh tranh bằng chứng trực tuyến” gượng và sai tai.',
  },
  {
    id: 'market-window-inside',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /Đó\s+là\s+cửa\s+sổ\s+bé,\s*nhưng\s+là\s+cửa\s+sổ\s+mở\s+vào\s+bên\s+trong/giu,
    replacement: 'Manh mối nhỏ, nhưng đủ để tôi lần vào bên trong',
    message: 'Ẩn dụ cửa sổ lặp và hơi AI.',
  },
  {
    id: 'market-knot-loosened',
    category: 'ai_metaphor',
    severity: 'medium',
    mode: 'replace',
    pattern: /một\s+nút\s+thắt\s+được\s+nới\s+một\s+chút/giu,
    replacement: 'ít nhất tôi đã kéo được một đầu mối ra ánh sáng',
    message: 'Ẩn dụ quen, hơi chung chung.',
  },
  {
  id: 'user-smile-long-enough-uncomfortable',
  category: 'collocation',
  severity: 'medium',
  mode: 'replace',
  pattern: /nụ\s+cười\s+kéo\s+dài\s+đúng\s+mức\s+để\s+người\s+khác\s+thấy\s+khó\s+chịu/giu,
  replacement: 'nụ cười giữ lâu hơn mức cần thiết, khiến người đối diện khó chịu',
  message: '“Kéo dài đúng mức” hơi gượng; đổi thành cách tả tự nhiên hơn.',
},
{
  id: 'user-eyes-stick-to-object',
  category: 'collocation',
  severity: 'medium',
  mode: 'template-replace',
  pattern: /mắt\s+tôi\s+dính\s+vào\s+([^.!?\n]{2,80})/giu,
  replacement: 'tôi nhìn chằm chằm vào $1',
  message: '“Mắt dính vào” dùng được nhưng lặp nhiều sẽ thô; đổi sang diễn đạt tự nhiên.',
},
{
  id: 'user-heart-not-fast-eye-sinks',
  category: 'unclear_sentence',
  severity: 'medium',
  mode: 'replace',
  pattern: /Tim\s+không\s+đập\s+nhanh,\s*chỉ\s+có\s+đáy\s+mắt\s+hơi\s+chùng/giu,
  replacement: 'Tôi không hoảng, chỉ thấy trong lòng nặng xuống',
  message: '“Đáy mắt hơi chùng” gượng và khó hình dung.',
},
{
  id: 'user-not-here-to-praise',
  category: 'collocation',
  severity: 'low',
  mode: 'replace',
  pattern: /Không\s+phải\s+họ\s+vào\s+để\s+khen/giu,
  replacement: 'Nhìn vẻ mặt họ, tôi biết chuyện này không phải lời khen',
  message: 'Câu cũ hơi cụt; đổi thành phản ứng tự nhiên hơn.',
},
{
  id: 'user-warm-because-hand-touched',
  category: 'ai_metaphor',
  severity: 'medium',
  mode: 'template-replace',
  pattern: /([^.!?\n]{2,80})\s+vẫn\s+ấm\s+vì\s+tay\s+tôi\s+vừa\s+chạm/giu,
  replacement: '$1 vẫn nằm trong túi áo tôi',
  message: '“Vật chứng vẫn ấm vì tay chạm” hơi văn AI; đổi thành chi tiết gọn.',
},
{
  id: 'user-signs-clearer-than-words',
  category: 'ai_metaphor',
  severity: 'medium',
  mode: 'template-replace',
  pattern: /những\s+dấu\s+lẻ\s+tỏ\s+ra\s+rõ\s+ràng\s+hơn\s+cả\s+lời\s+nói/giu,
  replacement: 'những chi tiết nhỏ ấy rõ hơn bất kỳ lời giải thích nào',
  message: '“Dấu lẻ tỏ ra” sai tai; đổi thành câu tự nhiên.',
},
{
  id: 'user-mirror-forces-meeting',
  category: 'ai_metaphor',
  severity: 'high',
  mode: 'replace',
  pattern: /tấm\s+gương\s+ép\s+họp/giu,
  replacement: 'bằng chứng buộc mọi người phải nhìn lại',
  message: '“Tấm gương ép họp” tối nghĩa, lộ AI.',
},
{
  id: 'user-many-i-still-have',
  category: 'repetition',
  severity: 'medium',
  mode: 'warn',
  pattern: /Tôi\s+còn\s+có\s+[^.!?\n]{2,80}\.\s*Tôi\s+còn\s+có/giu,
  message: 'Hai câu liên tiếp “Tôi còn có...” làm nhịp đều và máy; nên đổi một câu sang hành động cụ thể.',
  genericSuggestion: 'Ví dụ: “Tấm ảnh gốc nằm trong túi áo. Còn sợi chỉ, tôi đã giao cho người giữ biên bản.”',
},
{
  id: 'user-technical-proof-loop-print-log-invoice',
  category: 'plot_motif',
  severity: 'medium',
  mode: 'warn',
  pattern: /(?:biên\s+nhận|nhật\s+ký\s+in|file|invoice|bản\s+nháp|gửi\s+nhầm|clip|ảnh\s+gốc)(?:[^.!?\n]{0,80})(?:biên\s+nhận|nhật\s+ký\s+in|file|invoice|bản\s+nháp|gửi\s+nhầm|clip|ảnh\s+gốc)/giu,
  message: 'Chương đang gom quá nhiều vật chứng dạng kỹ thuật/in ấn/file. Dễ lặp motif và làm truyện dài bị khô.',
  genericSuggestion: 'Mỗi chương chỉ nên có 1 vật chứng chính. Xen kẽ bằng đối đầu người thật, mất mát thật, lời khai đổi hướng, hoặc phản diện tự lộ sơ hở.',
},
{
  id: 'market-voice-through-teeth-challenge',
  category: 'ai_metaphor',
  severity: 'medium',
  mode: 'replace',
  pattern: /giọng\s+rỉ\s+qua\s+răng\s+như\s+thách\s+thức/giu,
  replacement: 'giọng anh ta hạ thấp, đầy vẻ khiêu khích',
  message: '“Giọng rỉ qua răng” gượng và hơi lộ AI; đổi thành phản ứng giọng cụ thể.',
},
{
  id: 'market-every-look-waiting-apology',
  category: 'ai_metaphor',
  severity: 'medium',
  mode: 'replace',
  pattern: /mọi\s+cái\s+nhìn\s+đều\s+chực\s+chờ\s+một\s+câu\s+xin\s+lỗi\s+để\s+đóng\s+vết/giu,
  replacement: 'mọi người đều đang chờ tôi xin lỗi để kết luận chuyện này',
  message: '“Đóng vết” trong ngữ cảnh này hơi gượng; đổi thành ý trực tiếp, dễ đọc.',
},
{
  id: 'market-pr-not-smoke',
  category: 'unclear_sentence',
  severity: 'medium',
  mode: 'replace',
  pattern: /Làm\s+PR\s+không\s+phải\s+để\s+tóe\s+khói,\s*mà\s+để\s+chuyển\s+luồng/giu,
  replacement: 'Làm PR không phải để cãi thắng ngay tại chỗ, mà là đổi hướng chú ý của đám đông',
  message: '“Tóe khói” hơi lệch văn cảnh; sửa thành ý rõ hơn.',
},
{
  id: 'market-small-bone-spine-clue',
  category: 'ai_metaphor',
  severity: 'high',
  mode: 'replace',
  pattern: /nó\s+như\s+một\s+mảnh\s+xương\s+sống\s+nhỏ\s+để\s+bám\s+vào/giu,
  replacement: 'nó là thứ duy nhất tôi có thể bám vào lúc này',
  message: 'Ẩn dụ “mảnh xương sống nhỏ” gượng và hơi dị; đổi thành câu tự nhiên.',
},
{
  id: 'market-steps-arrow-into-case',
  category: 'ai_metaphor',
  severity: 'medium',
  mode: 'replace',
  pattern: /mỗi\s+bước\s+là\s+một\s+mũi\s+tên\s+vào\s+cuộc/giu,
  replacement: 'mỗi bước đều đưa tôi gần hơn tới người đứng sau chuyện này',
  message: 'Ẩn dụ “mũi tên vào cuộc” tối nghĩa; đổi thành hướng truy tìm cụ thể.',
},
{
  id: 'market-phone-like-stone-face',
  category: 'ai_metaphor',
  severity: 'medium',
  mode: 'replace',
  pattern: /tiếng\s+chuông\s+nhỏ\s+của\s+diễn\s+đàn\s+trường\s+lại\s+như\s+hòn\s+đá\s+ném\s+vào\s+mặt/giu,
  replacement: 'mỗi thông báo từ diễn đàn trường lại khiến tôi căng thẳng thêm',
  message: 'Ẩn dụ hơi nặng và lộ AI; đổi thành cảm giác trực tiếp.',
},
{
  id: 'market-comments-applaud-virtual',
  category: 'collocation',
  severity: 'medium',
  mode: 'replace',
  pattern: /mọi\s+người\s+vỗ\s+tay\s+dưới\s+bình\s+luận\s+ảo/giu,
  replacement: 'bên dưới lập tức có người hùa theo',
  message: '“Vỗ tay dưới bình luận ảo” không tự nhiên; đổi thành hành vi mạng xã hội quen hơn.',
},
{
  id: 'market-cold-corner-neck',
  category: 'ai_metaphor',
  severity: 'medium',
  mode: 'replace',
  pattern: /Một\s+góc\s+lạnh\s+chớm\s+lên\s+cổ\s+tôi/giu,
  replacement: 'Tôi thấy gáy mình lạnh đi',
  message: 'Câu cũ gượng; câu mới ngắn và tự nhiên hơn.',
},
{
  id: 'market-air-has-crack',
  category: 'ai_metaphor',
  severity: 'medium',
  mode: 'replace',
  pattern: /không\s+khí\s+như\s+có\s+một\s+vết\s+nứt/giu,
  replacement: 'không khí trong tiệm đã khác hẳn',
  message: 'Ẩn dụ “không khí có vết nứt” hơi AI; đổi thành nhận xét tự nhiên.',
},
{
  id: 'market-pull-this-wire',
  category: 'ai_metaphor',
  severity: 'medium',
  mode: 'replace',
  pattern: /phải\s+kéo\s+cái\s+dây\s+này\s+lên,\s*dù\s+đầu\s+dây\s+có\s+bị\s+ai\s+nắm\s+chặt\s+đến\s+đâu/giu,
  replacement: 'tôi phải lần theo manh mối này, dù người đứng sau có cố giấu đến đâu',
  message: 'Ẩn dụ dây hơi quen và dài; đổi thành câu điều tra rõ hơn.',
}
{
  id: 'market-smile-leaks-dry',
  category: 'collocation',
  severity: 'high',
  mode: 'replace',
  pattern: /Tôi\s+lòi\s+ra\s+một\s+nụ\s+cười\s+khô/giu,
  replacement: 'Tôi cười khẽ, nhưng trong lòng lạnh hẳn',
  message: '“Lòi ra một nụ cười khô” sai tai, giống convert; đổi thành phản ứng tự nhiên hơn.',
},
{
  id: 'market-eyes-stick-to-me',
  category: 'collocation',
  severity: 'medium',
  mode: 'replace',
  pattern: /Ánh\s+mắt\s+bà\s+dính\s+tôi/giu,
  replacement: 'Ánh mắt bà bám lấy tôi',
  message: '“Ánh mắt dính tôi” gượng; “bám lấy tôi” tự nhiên hơn.',
},
{
  id: 'market-measuring-gaze-wrong',
  category: 'unclear_sentence',
  severity: 'high',
  mode: 'replace',
  pattern: /vẻ\s+đo\s+thị/giu,
  replacement: 'vẻ dò xét',
  message: '“Vẻ đo thị” là cụm sai/convert; đổi thành “vẻ dò xét”.',
},
{
  id: 'market-dialogue-tight-like-string',
  category: 'ai_metaphor',
  severity: 'medium',
  mode: 'replace',
  pattern: /Đoạn\s+đối\s+thoại\s+giữa\s+chúng\s+tôi\s+căng\s+như\s+sợi\s+dây\s+đàn/giu,
  replacement: 'Không khí trong phòng căng hẳn lên',
  message: 'Ẩn dụ “đối thoại căng như sợi dây đàn” hơi cũ và lộ AI; đổi thành cảm giác trực tiếp.',
},
{
  id: 'market-each-sentence-like-brick',
  category: 'ai_metaphor',
  severity: 'medium',
  mode: 'replace',
  pattern: /Mỗi\s+câu\s+đều\s+như\s+một\s+viên\s+gạch\s+đặt\s+vào\s+nền\s+móng\s+của\s+một\s+bẫy\s+lớn\s+hơn/giu,
  replacement: 'Mỗi câu nói ra đều khiến cái bẫy phía sau rõ thêm một chút',
  message: 'Ẩn dụ “viên gạch/nền móng” dài và hơi AI; đổi thành câu rõ nghĩa hơn.',
},
{
  id: 'market-cold-like-knife-overused',
  category: 'ai_metaphor',
  severity: 'low',
  mode: 'warning',
  pattern: /giọng\s+[^.!?\n]{0,20}\s+cắt\s+như\s+dao|giọng\s+[^.!?\n]{0,20}\s+như\s+dao/giu,
  message: '“Giọng như dao/cắt như dao” dùng được nhưng đã sáo. Chỉ cảnh báo, không auto sửa nếu câu vẫn hợp nhịp truyện mạng.',
},
]
